// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export type RecordCountsDto = { observations: number, events: number, entities: number, relations: number, documents: number, assertions: number, total: number, };
