// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeDto } from "./EnvelopeDto";

export type AssertionDto = { id: string, dedup_key: string | null, 
/**
 * The entity making the claim (lifted from the `EntityId`
 * vocab newtype to a plain string).
 */
claimant: string, 
/**
 * Stance toward the content — `"asserted"`, `"denied"`,
 * `"hedged"`, etc. (matches the [`Stance`] enum's
 * snake_case wire form).
 */
stance: string, 
/**
 * The asserted content as opaque JSON. The
 * [`AssertedContent`] enum has a `kind` discriminator with
 * per-variant payload; the frontend reads the `kind` and
 * dispatches.
 */
content: unknown, envelope: EnvelopeDto, };
