// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeDto } from "./EnvelopeDto";

export type AssertionDto = { id: string, dedup_key: string | null, 
/**
 * The entity making the claim (lifted from the `EntityId`
 * vocab newtype to a plain string).
 */
claimant: string, 
/**
 * Stance toward the content — `"asserted"`, `"denied"`,
 * `"hedged"`, etc. (matches the [`Stance`] enum's
 * snake_case wire form).
 */
stance: string, 
/**
 * The asserted content as opaque JSON. The
 * [`AssertedContent`] enum has an `asserted_kind`
 * discriminator (renamed in Session 78 from `kind` to avoid a
 * collision with `RelationContent.kind`) with per-variant
 * payload; the frontend reads `content.asserted_kind` and
 * dispatches.
 */
content: unknown, envelope: EnvelopeDto, };
