// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorityEntryDto } from "./AuthorityEntryDto";

/**
 * Wire shape for the `authoritative_registry_summary` command
 * (Session 84). Surfaces what the operator needs to see in the
 * dashboard tile without having to grep the TOML:
 *   - how many entries are loaded
 *   - where they were loaded from
 *   - the entries themselves (capped — we don't expect this to
 *     grow beyond a few dozen rows; full transparency keeps the
 *     "is this entry actually being applied?" question one
 *     glance away).
 *
 * The summary is read live from the
 * [`situation_room_pipeline::authoritative_live::LiveAuthorityRegistry`]
 * in AppState so a hot-reload edit propagates to the next call.
 */
export type AuthorityRegistrySummaryDto = { 
/**
 * Total entry count.
 */
entry_count: number, 
/**
 * File path the registry was loaded from. Surfaced verbatim so
 * an operator can pin down which TOML the binary is reading.
 */
source_path: string, 
/**
 * The full set of loaded entries (capped to
 * [`AUTHORITY_SUMMARY_CAP`] for safety; realistic deployments
 * stay well under that).
 */
entries: Array<AuthorityEntryDto>, 
/**
 * True iff `entries` was clipped at the cap.
 */
entries_capped: boolean, };
