// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry surface for the dashboard tile. Mirrors the on-disk
 * `[[authority]]` row shape with all optional gates exposed.
 *
 * `consensus_quorum` reflects the Session-84 override: `None` /
 * `Some(1)` means the entry fast-tracks at N=1 via the authoritative
 * pass; `Some(n >= 2)` opts out of fast-track and lowers the
 * consensus quorum bar for groups containing the matching claimant.
 */
export type AuthorityEntryDto = { source_id: string, metric: string | null, topic: string | null, consensus_quorum: number | null, };
