// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the recipe-author prompt's document excerpt came from.
 * Wire mirror of [`situation_room_storage::AuthoredFrom`]. ADR 0014.
 *
 * ## Why a separate DTO type rather than `#[derive(TS)]` on the
 * storage enum
 *
 * Storage doesn't take ts-rs as a dependency (same boundary
 * rationale as for `RecipeDto` vs the typed `FetchRecipe` — see the
 * long comment above). A small mirror here keeps storage free of
 * tooling deps and gives the frontend a stable type at exactly one
 * location. The `From` impl below is the single conversion point.
 *
 * ## Wire form discipline
 *
 * `serde(rename_all = "snake_case")` matches the storage enum
 * byte-for-byte, so values produced by either side deserialize on
 * the other. The frontend's `AuthoredFromDto` TS type is a literal
 * union of the same three strings.
 */
export type AuthoredFromDto = "fetched_bytes" | "stub_excerpt" | "unknown";
