// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for the `classifier_prompt_version` command. One field
 * today (`current`) — the version string of the classifier prompt
 * the binary loaded. Wrapped in a struct rather than returned bare
 * so a future addition (e.g. a `changelog_summary` field, or a
 * per-provider version mapping) doesn't break the wire contract.
 */
export type ClassifierPromptVersionDto = { 
/**
 * The shipping prompt version (e.g. `"2.2"`). The frontend
 * compares this character-wise against the `@version` suffix
 * parsed off each plan's `classified_by` field to decide
 * whether to render the re-classify banner.
 */
current: string, };
