// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandErrorDto = { "kind": "invalid_input", field: string, message: string, } | { "kind": "classification_failed", message: string, } | { "kind": "storage", message: string, } | { "kind": "not_found", id: string, };
