// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-shape mirror of [`crate::commands::CommandError`]. We don't
 * derive TS on the real `CommandError` because `thiserror`'s
 * `#[derive(Error)]` interaction with `#[serde(tag = …)]` plus
 * `ts-rs`'s tagged-enum support is finicky; this shadow type gives
 * the frontend a clean discriminated union to match on.
 *
 * Keep in lockstep with `CommandError`. The unit tests in
 * `commands.rs` check the JSON shape; this type is just the TS
 * declaration the frontend consumes.
 */
export type CommandErrorDto = { "kind": "invalid_input", field: string, message: string, } | { "kind": "classification_failed", message: string, } | { "kind": "storage", message: string, } | { "kind": "not_found", id: string, } | { "kind": "fetch_failed", recipes_attempted: number, recipes_succeeded: number, message: string, };
