// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeDto } from "./EnvelopeDto";

/**
 * Wire shape for a Document record.
 *
 * Fields are flat (no nested `content` blob): a Document's payload
 * IS its envelope plus title/kind/mime/body/published_at/author.
 * No JSON-path lookup needed for the top-line summary.
 *
 * `body` may be large (extracted PDF text, full HTML article).
 * The frontend only renders the title in the card view; the body
 * is available for the expanded view if/when one is built.
 */
export type DocumentDto = { id: string, dedup_key: string | null, title: string | null, kind: string, mime: string, body: string, published_at: string | null, author: string | null, envelope: EnvelopeDto, };
