// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for the legacy pre-Session-37 document-source hint.
 * Surfaced under [`DocumentSourceEntryDto::Legacy`] only — newly
 * classified plans never produce this variant. Kept on the wire so
 * the frontend can render a "legacy entry — re-classify to update"
 * stub for plans persisted before ADR 0015.
 */
export type DocumentSourceHintDto = { description: string, preferred_source_ids: Array<string>, };
