// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriorityTierDto } from "./PriorityTierDto";

/**
 * Wire shape for a post-ADR-0015 document-source nomination. The
 * classifier emits the URL directly; the executor authors against
 * it without any registry lookup.
 */
export type DocumentSourceNominationDto = { description: string, endpoint_url: string, priority_tier: PriorityTierDto, 
/**
 * `null` on the wire when the LLM did not stamp a known_id (the
 * cold-start case). The frontend uses presence to decide whether
 * to show the recognized-source badge.
 */
known_id: string | null, };
