// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentSourceHintDto } from "./DocumentSourceHintDto";
import type { DocumentSourceNominationDto } from "./DocumentSourceNominationDto";

/**
 * Wire shape for one document-source entry on a plan.
 *
 * Tagged on the wire (`{"kind": "nomination", ...}` / `{"kind":
 * "legacy", ...}`) even though the on-disk `DocumentSourceEntry`
 * is `#[serde(untagged)]`. The asymmetry is deliberate: the
 * untagged-on-disk form lets old plans round-trip without touching
 * storage, and the tagged-on-wire form gives the React/Svelte
 * boundary a clean discriminator to pattern-match on.
 *
 * The frontend should:
 *
 * - For `Nomination`: render the new tile with the URL, tier, and
 *   optional known_id badge.
 * - For `Legacy`: render a "legacy entry — re-classify to update"
 *   stub. The plan was classified before Session 37 / ADR 0015
 *   and its sources cannot be authored against without re-classification.
 */
export type DocumentSourceEntryDto = { "kind": "nomination" } & DocumentSourceNominationDto | { "kind": "legacy" } & DocumentSourceHintDto;
