// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriorityTierDto } from "./PriorityTierDto";

/**
 * Wire shape for a post-Session-39 document-source nomination.
 *
 * The classifier no longer emits URLs; URL discovery happens in the
 * fetch executor's per-attempt propose-URL step. The plan persists
 * only what it needs to drive that step: a stable `nomination_id`
 * (server-stamped UUIDv7), a description specific enough that the
 * propose-URL LLM can locate a real endpoint, and a priority tier
 * for source-priority ordering in the UI.
 */
export type DocumentSourceNominationDto = { 
/**
 * UUIDv7 stamped at classify time. Stable across re-runs of the
 * same plan even when the retry loop picks different URLs each
 * run. Used as the `dedup_key` component on recipes; surfaces
 * in the UI for traceability but is not the operator-friendly
 * id on most screens.
 */
nomination_id: string, description: string, priority_tier: PriorityTierDto, };
