// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeDto } from "./EnvelopeDto";

export type EntityDto = { id: string, 
/**
 * Stable business identifier (the [`EntityId`] vocab type).
 */
entity_id: string, kind: string, canonical_name: string, 
/**
 * Geometry as opaque JSON (lat/long, polygons, etc.).
 * `None` when the entity has no spatial location.
 */
geometry: unknown | null, envelope: EnvelopeDto, };
