// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed-vocabulary wire shape for [`situation_room_storage::EntityProvenanceTier`].
 *
 * Strings mirror the variant names so the frontend can switch on a
 * stable token. `Unknown` is included for defence-in-depth: if a
 * future row's `provenance.license` falls outside the closed three,
 * the storage layer maps it to `Unknown` and the panel renders it as
 * a tier transition involving an unknown bucket — better than
 * hiding the row.
 */
export type EntityProvenanceTierDto = "Unknown" | "RecipeIterator" | "SlugHumanised" | "DocumentExtracted";
