// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntityKindExpectationDto = { kind: string, exemplars: Array<string>, 
/**
 * Session 81 — closed-vocabulary attribute keys for this entity
 * kind. Empty for plans classified before Session 81 (the field
 * carries `#[serde(default)]` in the typed `EntityKindExpectation`
 * upstream). The dashboard's entity tiles read this to surface the
 * extracted attribute facts that are in scope for the kind.
 */
attributes: Array<string>, rationale: string, };
