// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityProvenanceTierDto } from "./EntityProvenanceTierDto";

/**
 * One refresh event from the storage layer's ring buffer (Sn-99 #4).
 * The `EntityRefreshPanel` renders these as a stack of recent rows
 * so operators can see when an Entity's canonical_name was elevated
 * from a placeholder slug to a properly-extracted display name (or
 * any other tier elevation).
 *
 * `at` is RFC-3339 (UTC) — same posture as `LlmCostTimelineEntryDto`.
 */
export type EntityRefreshEventDto = { at: string, entity_id: string, previous_canonical_name: string, new_canonical_name: string, previous_tier: EntityProvenanceTierDto, new_tier: EntityProvenanceTierDto, 
/**
 * `true` iff `previous_canonical_name != new_canonical_name`.
 * Pre-computed Rust-side so the frontend doesn't have to do a
 * string compare per row at render time.
 */
name_changed: boolean, };
