// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProvenanceDto } from "./ProvenanceDto";
import type { SubjectsDto } from "./SubjectsDto";

/**
 * Wire shape for [`situation_room_core::Envelope`].
 *
 * Carries provenance, subjects, audit timestamps, confidence. The
 * `subjects.places` and `subjects.time` fields are kept opaque
 * (`unknown` in TS) because place geometry and time-scope
 * shapes haven't stabilized for the rendering side yet — a Session
 * 22+ rendering pass that needs them can promote those to typed
 * DTOs without a wire break.
 */
export type EnvelopeDto = { provenance: ProvenanceDto, subjects: SubjectsDto, tags: Array<string>, 
/**
 * Validity timestamp, in ISO 8601. `None` for records that
 * don't carry one (Documents, Entities, the open valid window
 * of an Observation).
 */
valid_at: string | null, 
/**
 * When the system observed the record (the fetch timestamp,
 * roughly). Always populated.
 */
observed_at: string, 
/**
 * Confidence in [0.0, 1.0]. The vocab newtype clamps; the
 * wire shape is a plain f32.
 */
confidence: number, };
