// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeDto } from "./EnvelopeDto";

export type EventDto = { id: string, dedup_key: string | null, envelope: EnvelopeDto, content: unknown, };
