// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recipe in the per-expectation `recipes` list.
 *
 * Carries enough to render a chip: the recipe's id (for linking back
 * to the recipe panel) and the source it fetches from.
 */
export type ExpectationCoverageRecipeDto = { recipe_id: string, source_id: string, 
/**
 * The `record_type` of the binding ("observation" | "event" |
 * "relation"). Useful when a recipe binds to multiple
 * expectations in different buckets — the chip shows the type so
 * the operator can confirm the recipe targets the bucket they're
 * looking at.
 */
record_type: string, };
