// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpectationCoverageRecipeDto } from "./ExpectationCoverageRecipeDto";

/**
 * One row in the plan-expectation coverage matrix.
 *
 * For each plan expectation (identified by `bucket` + `index`), the
 * matrix lists which recipes target it via their `produces[].expectation`
 * references. Uncovered buckets surface explicitly: the entry is
 * returned with `recipes` empty so the frontend renders a "uncovered"
 * marker rather than silently dropping the row.
 *
 * The plan's `interpretation` paragraph and topic_tags are out of
 * scope here — they're carried by `ResearchPlanDto` already.
 *
 * ## Why per-(bucket, index) rows rather than per-bucket
 *
 * A bucket can have multiple expectations (e.g. plan 019e0b21's
 * observation_metrics has 4: production, reserves, refining_capacity,
 * spot_price). The recipe-author prompt's coverage discipline
 * (v1.14 §"Coverage discipline — bindings vs expectations")
 * deliberately accepts narrow honest coverage where one recipe
 * targets one expectation index. Surfacing per-index rows is what
 * makes that narrowness legible — a per-bucket roll-up would
 * collapse "production covered, reserves and refining_capacity not"
 * into a single "1 of 4" cell that obscures *which* of the four.
 */
export type ExpectationCoverageRowDto = { 
/**
 * One of `observation_metric` | `event_type` | `entity_kind` |
 * `relation_kind`. The same string the recipe's
 * `produces[].expectation.list` uses. (Document and Assertion
 * expectations are not addressed by recipe `produces` bindings;
 * they're surfaced through other surfaces and not part of this
 * matrix.)
 */
bucket: string, 
/**
 * 0-indexed position within the bucket. Matches the recipe's
 * `produces[].expectation.index`.
 */
index: number, 
/**
 * The expectation's primary identifier as the user would read it
 * in the bucket panel — `metric.name` for observation,
 * `event.event_type` for event, etc. Empty string if the bucket
 * has fewer entries than `index`, which would only happen if the
 * plan's expectations changed between recipe authoring and this
 * query (rare but defensive).
 */
label: string, 
/**
 * Recipes whose `produces[].expectation` reference points at this
 * (bucket, index). Empty Vec for uncovered expectations.
 */
recipes: Array<ExpectationCoverageRecipeDto>, };
