// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-failure stage on the wire. Mirrors
 * [`stockpile_pipeline::fetch_executor::FailureStage`].
 */
export type FailureStageDto = "fetch" | "apply" | "insert";
