// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary row for the fetch-runs list.
 *
 * `started_at` and `finished_at` are full timestamps; the frontend
 * formats them locally. `finished_at` of `null` means the run is
 * still in flight (or — in the corner case where closing the row
 * failed — the final write was lost; the next session's UI may want
 * to surface that state distinctly, but for now an open-looking row
 * is treated as in-flight).
 */
export type FetchRunSummaryDto = { id: string, plan_id: string, started_at: string, finished_at: string | null, recipes_attempted: number, recipes_succeeded: number, records_produced: number, error_summary: string | null, };
