// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeOutcomeDto } from "./RecipeOutcomeDto";

/**
 * Wire shape for one fetch run's outcome. Mirrors
 * [`situation_room_pipeline::fetch_executor::FetchReport`] one-for-one.
 *
 * Returned synchronously by the `run_fetch_for_plan` command. The
 * frontend renders it in the review pane so the user sees, in one
 * place, what each recipe produced.
 */
export type FetchReportDto = { plan_id: string, run_id: string, outcomes: Array<RecipeOutcomeDto>, recipes_attempted: number, recipes_succeeded: number, records_produced: number, error_summary: string | null, };
