// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeoScopeDto = { code: string, 
/**
 * Empty string means "no per-session display preference; render
 * `code`." Wire form matches `pipeline::research::GeoScope`.
 */
display: string, };
