// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-host row from the backoff layer's [`snapshot`] accessor.
 *
 * `wait_seconds_remaining` is `0` when the host is currently
 * unblocked. Distinguish "0 wait + counter > 0" (recovering — the
 * schedule expired but the failure history is still in effect for
 * the next signal) from "0 wait + counter == 0" (clean state — the
 * row exists only because a prior failure was reset by a successful
 * fetch).
 *
 * Today no IPC command exposes this DTO — it's carried as a
 * drive-by for piece B. Mounting an IPC command on top of it is a
 * one-screen change once piece B lands.
 *
 * [`snapshot`]: situation_room_pipeline::fetch_backoff::HostBackoff::snapshot
 */
export type HostBackoffSnapshotDto = { host: string, consecutive_failures: number, wait_seconds_remaining: bigint, };
