// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromoteReportFlatDto } from "./PromoteReportFlatDto";

/**
 * Wire shape for the `last_promote_summary` command (Session 84).
 * Surfaces the most recent completed promote run so the dashboard
 * tile can render "the last pass found X authoritative + Y
 * consensus groups" without grepping INFO logs.
 *
 * `trigger` carries the closed-vocab tag for why the pass fired
 * (`"auto_after_fetch"` or `"manual"`).
 * `at` is RFC-3339 (UTC) for IPC simplicity; the frontend parses
 * with `new Date(...)` when it needs a Date object.
 */
export type LastPromoteSummaryDto = { plan_id: string, at: string, trigger: string, report: PromoteReportFlatDto, };
