// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTierDto } from "./ModelTierDto";

/**
 * One entry in the per-call cost timeline (Session 81). Mirrors
 * [`situation_room_llm::TimelineEntry`] across the wire.
 *
 * `timestamp` is RFC-3339 string for IPC simplicity; the frontend
 * parses with `new Date(...)` when it needs a Date object.
 * `input_tokens`/`output_tokens`/`cached_input_tokens` are wrapped
 * in nullables (mapped from `Option<u32>`) so providers that don't
 * report a particular field don't have to invent a fake zero.
 */
export type LlmCostTimelineEntryDto = { timestamp: string, provider: string, tier: ModelTierDto, purpose: string | null, input_tokens: number | null, output_tokens: number | null, cached_input_tokens: number | null, };
