// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTierDto } from "./ModelTierDto";

/**
 * One row in the LLM cost-ledger surface. Mirrors
 * [`situation_room_llm::LedgerEntry`] one-for-one, with totals lifted
 * into the wire shape the dashboard tile reads.
 *
 * ## Cache-hit ratio is computed client-side
 *
 * We surface raw counts here — `input_tokens`, `cached_input_tokens`,
 * `calls_with_cache_data` — and let the frontend compute the ratio
 * when it has data to compute over. Wire-shape stability matters
 * across binary restarts more than the convenience of a pre-computed
 * float; the operator's eye lands on the chip the dashboard renders
 * regardless of where the divide happens.
 *
 * ## Why `calls_with_cache_data` is on the wire
 *
 * Distinguishes "provider doesn't report cache hits" (None) from
 * "cold prefix, reported zero" (Some(0)) for ratio purposes. See
 * the same field's doc on
 * [`situation_room_llm::cost_ledger::Tally`] for the underlying
 * invariant.
 */
export type LlmCostLedgerEntryDto = { 
/**
 * Provider id — the same string `LlmProvider::id()` returns
 * (`"xai"`, `"anthropic"`, …).
 */
provider: string, tier: ModelTierDto, calls: bigint, input_tokens: bigint, output_tokens: bigint, cached_input_tokens: bigint, 
/**
 * How many of `calls` reported a `Some(_)` for cached tokens;
 * denominator for the cache-hit ratio. A value of 0 means the
 * provider didn't report (the dashboard renders "—" rather than
 * "0%").
 */
calls_with_cache_data: bigint, };
