// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetricExpectationDto = { name: string, 
/**
 * Unit hint as a plain string (the pipeline's `Unit` newtype's
 * inner string). Empty when absent.
 */
unit_hint: string, rationale: string, };
