// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire mirror of [`situation_room_llm::ModelTier`]. ts-rs renders this
 * as a string-union type (`"frontier" | "workhorse" | "cheap"`) so the
 * frontend can use it as a label without re-encoding.
 *
 * Why a parallel DTO: `ModelTier` lives in the llm crate, which —
 * per the same posture as `MemorySource` in storage — doesn't depend
 * on `ts-rs`. The cost is one tiny enum mirror; the benefit is that
 * the llm crate stays free of UI-tooling deps.
 */
export type ModelTierDto = "frontier" | "workhorse" | "cheap";
