// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeDto } from "./EnvelopeDto";

/**
 * Wire shape for an Observation record.
 *
 * `content` carries the `ObservationContent` shape (metric, value,
 * unit, period, …) as opaque JSON. The frontend's
 * `formatRecordSummary` helper knows the shape informally and
 * pulls top-line fields (`metric`, `value`, `unit`) by JSON
 * path. See module docs for the rationale.
 */
export type ObservationDto = { id: string, dedup_key: string | null, envelope: EnvelopeDto, content: unknown, };
