// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state for a plan, as seen by the frontend. Mirrors
 * [`situation_room_storage::research_plans::PlanStatus`] one-for-one.
 *
 * The serde representation is lowercase and unit-tagged
 * (`"pending"` / `"accepted"` / `"rejected"`), matching both the
 * storage column form and the `serde(rename_all = "lowercase")` on
 * the underlying enum. Bend either side and the other follows; the
 * `command_error_dto` shadow-type pattern doesn't apply here because
 * `PlanStatus` is a plain unit enum and ts-rs handles those cleanly.
 */
export type PlanStatusDto = "pending" | "accepted" | "rejected";
