// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanSummary = { id: string, topic: string, created_at: string, topic_tag_count: number, observation_count: number, event_count: number, entity_count: number, relation_count: number, document_source_count: number, };
