// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source-priority tier on the wire. ADR 0015 / Session 37: closed
 * snake_case enum. Mirrors
 * [`situation_room_pipeline::research::PriorityTier`] one-for-one.
 */
export type PriorityTierDto = "authoritative_primary" | "authoritative_secondary" | "industry_trade_press" | "general_news";
