// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flattened mirror of `situation_room_pipeline::promote::PromoteReport`
 * — the wire shape exposed by `last_promote_summary`. Hand-mapped
 * (the Rust type derives `Serialize` but not `TS`; mirroring it
 * here keeps the desktop binary's ts-rs export self-contained).
 */
export type PromoteReportFlatDto = { assertions_considered: number, groups_promoted: number, skipped_already_promoted: number, observations_emitted: number, events_emitted: number, relations_emitted: number, entity_attributes_emitted: number, insert_failures: number, authoritative_promoted: number, };
