// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for [`situation_room_core::Provenance`].
 *
 * `source_id` is the full provenance string —
 * `"{src}#recipe:{recipe_uuid}@v{version}"` for records produced
 * by a recipe. `recipe_id` is the parsed recipe-uuid sub-component
 * surfaced as a separate field so the frontend can join records
 * to recipe cards without parsing.
 */
export type ProvenanceDto = { 
/**
 * The full provenance string as stamped by recipe_apply.
 */
source_id: string, 
/**
 * The parsed recipe id, when the provenance string follows the
 * recipe-stamped format. `None` for legacy records or records
 * whose source_id has some other shape.
 *
 * Empty-string-as-absent wire convention: `""` means "no recipe
 * id parseable from this provenance", which the frontend treats
 * as "no link to any recipe card." Mirrors the
 * `unit_hint` / `display` handling elsewhere in this crate.
 */
recipe_id: string, source_url: string | null, source_published_at: string | null, license: string, 
/**
 * Derivation chain as opaque JSON. The full
 * `Vec<DerivedFrom>` shape isn't rendered today (no records
 * derive from others until ADR 0004 assertion promotion is
 * implemented); typing it would be premature.
 */
derived_from: unknown, };
