// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for [`situation_room_core::Provenance`].
 *
 * `source_id` is the full provenance string —
 * `"{src}#recipe:{recipe_uuid}@v{version}"` for records produced
 * by a recipe. `recipe_id` is the parsed recipe-uuid sub-component
 * surfaced as a separate field so the frontend can join records
 * to recipe cards without parsing.
 */
export type ProvenanceDto = { 
/**
 * The full provenance string as stamped by recipe_apply.
 */
source_id: string, 
/**
 * The parsed recipe id, when the provenance string follows the
 * recipe-stamped format. `None` for legacy records or records
 * whose source_id has some other shape.
 *
 * Empty-string-as-absent wire convention: `""` means "no recipe
 * id parseable from this provenance", which the frontend treats
 * as "no link to any recipe card." Mirrors the
 * `unit_hint` / `display` handling elsewhere in this crate.
 */
recipe_id: string, source_url: string | null, source_published_at: string | null, license: string, 
/**
 * Derivation chain as opaque JSON. The full
 * `Vec<DerivedFrom>` shape isn't rendered today (no records
 * derive from others until ADR 0004 assertion promotion is
 * implemented); typing it would be premature.
 */
derived_from: unknown, 
/**
 * Session 87: closed-vocabulary selector_path. `None` for
 * promoted / derived / LLM-synthesized rows. The pipeline
 * (`recipe_apply::render_selector_path`) owns the format —
 * `"css:<sel>"`, `"json:<path>"`, `"csv:<col>@<filter>"`,
 * `"pdf:p<n>/t<n>/r<n>/c<n>"`, `"regex:group=<n>"`. Iterator-
 * mode recipes prefix `"<iter> >> "`.
 */
selector_path: string | null, 
/**
 * Session 87: short UTF-8 excerpt of the leaf bytes the recipe
 * extracted. `None` for non-recipe-derived rows. Capped at
 * `RAW_BYTES_EXCERPT_CAP` (256) codepoints inside the stamper;
 * a trailing `"…"` marks where the excerpt was truncated.
 */
raw_bytes_excerpt: string | null, };
