// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthoredFromDto } from "./AuthoredFromDto";

/**
 * Wire shape for a recipe as the frontend renders it in the
 * inspection panel.
 *
 * ## Why scalar fields are typed but `extraction` / `produces` aren't
 *
 * The internal [`situation_room_pipeline::recipes::FetchRecipe`] has
 * strongly-typed `extraction: ExtractionSpec` (closed enum of five
 * modes) and `produces: Vec<ProductionBinding>` (with nested closed
 * enums for `record_type`, `field_value_source`, etc.). Mirroring all
 * of that into ts-rs DTOs is feasible but adds a lot of code that the
 * frontend's recipe-inspection panel doesn't need: it renders these
 * fields as pretty-printed JSON for the user to read.
 *
 * So we type the scalar fields strongly (id, source_id, source_url,
 * version, authored_*) and leave the structured fields as
 * `serde_json::Value` on the wire (`unknown` in TypeScript). If a
 * future session wants per-mode rendering on the frontend, the DTO
 * can grow per-variant mirrors then. Pay for type safety when
 * rendering needs it; until then, the round-trip honesty of the JSON
 * is enough.
 *
 * ## Where this comes from
 *
 * Storage (`StoredRecipe`) carries `extraction_json: String` and
 * `produces_json: String` — JSON strings, not parsed values. The
 * `from_stored` constructor parses both back into `Value` so the
 * frontend doesn't have to do a `JSON.parse` at render time. A parse
 * failure surfaces as a structured error in the `extraction` /
 * `produces` field, which is honest about which recipe is broken
 * rather than 500-ing the whole listing.
 */
export type RecipeDto = { id: string, 
/**
 * `None` if the recipe was authored without a stable dedup key
 * (older entries; the executor stamps one as of Session 10).
 */
dedup_key: string | null, plan_id: string, source_id: string, source_url: string, 
/**
 * The extraction spec — mode + parameters. Opaque on the wire;
 * TypeScript sees `unknown` and the frontend pretty-prints.
 */
extraction: unknown, 
/**
 * The production bindings — record_type + field_mappings per
 * binding. Same opacity rationale as `extraction`.
 */
produces: unknown, authored_at: string, 
/**
 * Identifier for what authored this recipe — typically a
 * provider id like `"xai"` or `"recording"` (in tests).
 */
authored_by: string, version: number, 
/**
 * Bake-time-frozen payload (ADR 0007 Amendment 3). `None` for
 * the common HTML-addressable case (recipe fetches `source_url`
 * at runtime). `Some(payload)` means the recipe is "baked" —
 * the runtime serves these bytes to extraction in place of an
 * HTTP fetch, and the recipe will produce the same records
 * every fetch until re-authored. The frontend renders this
 * as a visible BAKED badge so the freshness model is explicit
 * in the UI.
 */
static_payload: string | null, 
/**
 * Where the recipe-author prompt's document excerpt came from
 * (real bytes vs. stub) at authoring time. ADR 0014.
 *
 * The frontend renders `StubExcerpt` as a visible
 * `STUB-AUTHORED` chip on the recipe card and as an
 * informational banner in the flag dialog. `FetchedBytes`
 * renders no chip (the absence is the signal: the recipe is
 * grounded). `Unknown` renders no chip either — it's the
 * pre-ADR-0014 legacy value, and showing a chip for "we don't
 * know" would create noise on every existing recipe in the
 * database the moment the operator updates.
 */
authored_from: AuthoredFromDto, 
/**
 * The recipe id this row supersedes, if any. ADR 0012 §"Storage:
 * recipe version chain". `None` for first-authored recipes (the
 * chain head); `Some(prior_id)` for re-authored recipes (Track
 * A, Session 25/26 — manual re-author UI). The frontend renders
 * `Some` as a small lineage chip in the recipe head, citing the
 * prior id.
 *
 * Wire form: empty-string-as-absent. The xAI structured-output
 * schema convention used elsewhere on this DTO doesn't apply
 * here (this DTO isn't an LLM output), but the same wire
 * shape is used so the frontend's "Some-vs-None" branch is
 * consistent across `static_payload`, `dedup_key`, and the
 * re-author lineage. `Option<String>` of a UUID string is
 * the chosen idiom — distinct from the typed `Uuid` so the
 * TypeScript surface stays a plain string.
 */
prior_recipe_id: string | null, 
/**
 * Why this recipe was re-authored, if it was. The persisted
 * short form: failure message + (optional) operator note. `None`
 * for first-authored recipes; `Some(text)` for re-authored ones.
 * Travels alongside [`Self::prior_recipe_id`]: a `Some(prior)`
 * row carries a `Some(reason)`. The frontend's lineage chip
 * surfaces the reason as a tooltip / details disclosure.
 */
reauthor_reason: string | null, };
