// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeOutcomesHistoryRunCellDto } from "./RecipeOutcomesHistoryRunCellDto";

/**
 * One row in the recipe-success heatmap.
 *
 * Identifies the (recipe-or-source, source) pair the row groups by:
 * - `recipe_id = Some(uuid)` for `succeeded` / `skipped` / `failed`
 *   / `rate_limited` outcomes (the recipe was authored).
 * - `recipe_id = None` for `declined` / `legacy_plan_cannot_author`
 *   outcomes (no recipe was authored; group key is `source_id`
 *   alone).
 *
 * `runs` is the per-run cell vec ordered oldest-first, so the
 * frontend renders runs left-to-right without sorting.
 */
export type RecipeOutcomesHistoryEntryDto = { recipe_id: string | null, source_id: string, runs: Array<RecipeOutcomesHistoryRunCellDto>, };
