// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-(recipe, run) attempt as it crosses the IPC boundary for the
 * re-author dialog. Track A. The dialog shows the failure message
 * verbatim and the bytes the runtime saw, so the operator reviews
 * the same evidence the LLM will see at re-author time.
 *
 * `bytes_excerpt` is the head of the response, capped server-side
 * at `MAX_EXCERPT_BYTES` (64 KiB; see
 * `crates/storage/src/recipe_fetch_attempts.rs`). The wire type is
 * `Option<String>` rather than always-string because:
 *
 *   - A failure stage *before* bytes were obtained (DNS, TCP,
 *     transport-level error before the body) leaves no excerpt.
 *   - A row from before this migration would also lack one.
 *
 * `failure_message` is similarly `Option<String>` for symmetry; in
 * practice every captured row from Track A has both populated, but
 * the wire shape doesn't pin that and shouldn't (storage can carry
 * looser shapes than the runtime emits).
 */
export type RecipeFetchAttemptDto = { id: string, recipe_id: string, run_id: string, attempted_at: string, succeeded: boolean, failure_message: string | null, bytes_excerpt: string | null, };
