// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailureStageDto } from "./FailureStageDto";

/**
 * One per-recipe outcome on the wire. Discriminated union with the
 * same shape as the Rust enum — the frontend pattern-matches on
 * `kind`.
 *
 * The discriminator naming follows the codebase's existing `kind`
 * convention (see `CommandErrorDto`). Adding a new outcome variant
 * is an additive change; the frontend's `kind` switch must add the
 * new arm or the type-checker will flag the missing case.
 *
 * ## Variants
 *
 * - `succeeded` — the recipe ran end-to-end and produced records.
 * - `skipped` — the executor declined to run the recipe (e.g.
 *   extraction mode not yet enabled in the runtime).
 * - `failed` — the recipe ran and broke at a named stage. The
 *   `stage` discriminator lets the UI render per-stage hints.
 * - `rate_limited` — Track D, Session 25. The source returned 429
 *   in a way the executor's inline backoff didn't wait through:
 *   either `Retry-After` exceeded the short-backoff ceiling, or no
 *   `Retry-After` was provided. The frontend renders this in
 *   warning amber to distinguish it from `failed` red — re-running
 *   later is meaningful for a rate-limit, pointless for a broken
 *   recipe.
 * - `declined` — Track B, Session 28, ADR 0007 amendment 4. The
 *   recipe-author LLM declined to write a recipe for this source
 *   and explained why. **No `recipe_id`** — no recipe was created.
 *   The frontend renders this in a distinct tone (`'declined'`) so
 *   the operator sees an authoring-stage decision, not a runtime
 *   failure. Remediation is editorial: drop the source, find an
 *   alternative, escalate the model tier — re-running the same
 *   inputs gets the same decline.
 */
export type RecipeOutcomeDto = { "kind": "succeeded", recipe_id: string, source_id: string, records_produced: number, } | { "kind": "skipped", recipe_id: string, source_id: string, reason: string, } | { "kind": "failed", recipe_id: string, source_id: string, stage: FailureStageDto, message: string, } | { "kind": "rate_limited", recipe_id: string, source_id: string, 
/**
 * Parsed `Retry-After` value in seconds, when the server
 * supplied one (per RFC 9110 §10.2.3). `None` means the
 * server returned 429 with no machine-readable hint. The
 * frontend formats both cases via `outcomes.ts`.
 */
retry_after_seconds: bigint | null, } | { "kind": "declined", source_id: string, reason: string, };
