// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-run cell inside a [`RecipeOutcomesHistoryEntryDto`]. Mirrors
 * [`situation_room_storage::fetch_run_outcomes::RecipeOutcomeHistoryRunRow`]
 * one-for-one with two tweaks for the wire:
 * - `run_id` becomes a string (matches the rest of the DTO surface).
 * - `outcome_kind` is a [`RecipeOutcomeDto::kind`]-shaped string
 *   chosen from the same closed set the live `FetchReportDto` uses,
 *   so the frontend's existing `outcomeTone` helper can render
 *   history cells identically to the live outcomes list.
 */
export type RecipeOutcomesHistoryRunCellDto = { run_id: string, attempted_at: string, 
/**
 * One of `succeeded` | `skipped` | `failed` | `rate_limited` |
 * `declined` | `legacy_plan_cannot_author` — the same closed set
 * `RecipeOutcomeDto::kind` uses. Stored as a string for ts-rs
 * simplicity; the frontend's `outcomeTone` helper takes a full
 * `RecipeOutcomeDto` so we synthesise one client-side from the
 * kind + payload fields below.
 */
outcome_kind: string, 
/**
 * `Some(n)` when `outcome_kind == "succeeded"`. `None` otherwise.
 */
records_produced: number | null, 
/**
 * `Some(n)` when `outcome_kind == "rate_limited"` and the server
 * supplied a Retry-After. `None` otherwise.
 */
retry_after_seconds: bigint | null, 
/**
 * `Some("fetch" | "apply" | "insert")` when `outcome_kind ==
 * "failed"`. `None` otherwise.
 */
failure_stage: string | null, 
/**
 * Human-readable detail: failure message, skip reason, or LLM
 * decline reason. `None` for `succeeded` / `rate_limited` /
 * `legacy_plan_cannot_author`.
 */
message: string | null, };
