// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailureStageDto } from "./FailureStageDto";

/**
 * One per-recipe outcome on the wire. Discriminated union with the
 * same shape as the Rust enum — the frontend pattern-matches on
 * `kind`.
 *
 * The discriminator naming follows the codebase's existing `kind`
 * convention (see `CommandErrorDto`). Adding a new outcome variant
 * is an additive change; the frontend's `kind` switch must add the
 * new arm or the type-checker will flag the missing case.
 */
export type RecipeOutcomeDto = { "kind": "succeeded", recipe_id: string, source_id: string, records_produced: number, } | { "kind": "skipped", recipe_id: string, source_id: string, reason: string, } | { "kind": "failed", recipe_id: string, source_id: string, stage: FailureStageDto, message: string, };
