// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-(plan, source) operator note attached via the recipe-inspection
 * panel's flag affordance. Fed back to the LLM as `{{RECIPE_FEEDBACK}}`
 * the next time recipe-authoring runs for the same (plan, source).
 *
 * Stored as a single row per (plan, source) — overwrite, not history
 * (ADR 0013 §"The overwrite choice"). The frontend renders the chip
 * next to the recipe card; hover surfaces the note text.
 *
 * Wire identifiers are `String`-form UUIDs to keep the TS type
 * consistent with `RecipeDto.plan_id` and `PlanSummary.id`. The
 * `created_at` carries the time the note was last set (so a re-flag
 * surfaces a fresh timestamp); on `clear`, the row is deleted and
 * no DTO is emitted.
 */
export type RecipeFeedbackDto = { plan_id: string, source_id: string, note: string, created_at: string, };
