// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentSourceEntryDto } from "./DocumentSourceEntryDto";
import type { EntityKindExpectationDto } from "./EntityKindExpectationDto";
import type { EventTypeExpectationDto } from "./EventTypeExpectationDto";
import type { MetricExpectationDto } from "./MetricExpectationDto";
import type { RelationKindExpectationDto } from "./RelationKindExpectationDto";

export type RecordExpectationsDto = { observation_metrics: Array<MetricExpectationDto>, event_types: Array<EventTypeExpectationDto>, entity_kinds: Array<EntityKindExpectationDto>, relation_kinds: Array<RelationKindExpectationDto>, document_sources: Array<DocumentSourceEntryDto>, 
/**
 * `None` is preserved as `null` on the wire; the frontend renders
 * the assertion-guidance panel only when present.
 */
assertion_guidance: string | null, };
