// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssertionDto } from "./AssertionDto";
import type { DocumentDto } from "./DocumentDto";
import type { EntityDto } from "./EntityDto";
import type { EventDto } from "./EventDto";
import type { ObservationDto } from "./ObservationDto";
import type { RelationDto } from "./RelationDto";

/**
 * Wire shape for [`situation_room_storage::RecordsByPlan`].
 *
 * Per-type Vecs, mirroring the storage shape. The frontend's
 * six-bucket panel grid maps one bucket to one Vec; rendering is
 * a straight iteration with no client-side partitioning.
 */
export type RecordsByPlanDto = { observations: Array<ObservationDto>, events: Array<EventDto>, entities: Array<EntityDto>, relations: Array<RelationDto>, documents: Array<DocumentDto>, assertions: Array<AssertionDto>, };
