// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelationTripleExemplarDto } from "./RelationTripleExemplarDto";

export type RelationKindExpectationDto = { kind: string, 
/**
 * Session 77 — prototype `(from, to)` triples the classifier
 * nominated for this kind. Empty for plans classified before
 * Session 77 and for kinds the classifier didn't seed from
 * prior knowledge. The plan-review surface renders these as
 * chips under the kind tile so the operator can spot which
 * concrete edges materialised on accept.
 */
exemplar_triples: Array<RelationTripleExemplarDto>, rationale: string, };
