// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for one prototype `(from, to)` relation triple.
 * Endpoints arrive as plain strings (the typed `EntityId`'s inner
 * `prefix:slug` form). The kind lives on the parent
 * [`RelationKindExpectationDto`].
 */
export type RelationTripleExemplarDto = { from: string, to: string, 
/**
 * Empty string when the classifier didn't attach a rationale.
 * Matches the empty-string-as-absent convention used elsewhere
 * in this DTO file (`unit_hint`, `display`, …).
 */
rationale: string, };
