// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoScopeDto } from "./GeoScopeDto";
import type { PlanStatusDto } from "./PlanStatusDto";
import type { RecordExpectationsDto } from "./RecordExpectationsDto";

/**
 * Wire shape for a research plan. Mirrors
 * [`situation_room_pipeline::research::ResearchPlan`] one-for-one, with
 * the storage-layer audit field [`status`](Self::status) tacked on so
 * the frontend can render the lifecycle pill / accept-reject buttons
 * without a second IPC roundtrip.
 *
 * ## Why every nested type is also a DTO
 *
 * `ts-rs` generates each `#[derive(TS)]` type independently. If we
 * embedded the pipeline's `MetricExpectation` directly here, it would
 * have to derive `TS` too — pulling ts-rs into the pipeline crate.
 * Mirroring the shape with local types keeps the dependency direction
 * clean: `pipeline` doesn't know about ts-rs; `api` owns the wire
 * schema.
 */
export type ResearchPlanDto = { id: string, topic: string, interpretation: string, topic_tags: Array<string>, geographic_scope: Array<GeoScopeDto>, historical_window_days: number, expectations: RecordExpectationsDto, created_at: string, status: PlanStatusDto, 
/**
 * Free-text note the user attached when rejecting. Empty string
 * for plans that were never rejected, plans rejected before
 * Session 15, and rejections where the user supplied no note.
 * Empty-string-as-absent matches the wire convention for
 * optional strings throughout the api crate (see `unit_hint`,
 * `display`, etc.); we don't introduce a separate `null` shape
 * here for parity.
 */
rejection_reason: string, 
/**
 * UUID of the rejected plan that prompted this re-classification,
 * as a string. Empty string when this plan was not produced by
 * the re-classify-with-feedback flow. Stringly-typed on the wire
 * for the same reason `id` is — ts-rs doesn't have a Uuid
 * primitive at the TS side.
 */
reclassified_from: string, };
