// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoScopeDto } from "./GeoScopeDto";
import type { PlanStatusDto } from "./PlanStatusDto";
import type { RecordExpectationsDto } from "./RecordExpectationsDto";

/**
 * Wire shape for a research plan. Mirrors
 * [`situation_room_pipeline::research::ResearchPlan`] one-for-one, with
 * the storage-layer audit field [`status`](Self::status) tacked on so
 * the frontend can render the lifecycle pill / accept-reject buttons
 * without a second IPC roundtrip.
 *
 * ## Why every nested type is also a DTO
 *
 * `ts-rs` generates each `#[derive(TS)]` type independently. If we
 * embedded the pipeline's `MetricExpectation` directly here, it would
 * have to derive `TS` too — pulling ts-rs into the pipeline crate.
 * Mirroring the shape with local types keeps the dependency direction
 * clean: `pipeline` doesn't know about ts-rs; `api` owns the wire
 * schema.
 */
export type ResearchPlanDto = { id: string, topic: string, interpretation: string, topic_tags: Array<string>, geographic_scope: Array<GeoScopeDto>, historical_window_days: number, expectations: RecordExpectationsDto, created_at: string, status: PlanStatusDto, };
