// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { GeoScopeDto } from "./GeoScopeDto";
import type { RecordExpectationsDto } from "./RecordExpectationsDto";

export type ResearchPlanDto = { id: string, topic: string, interpretation: string, topic_tags: Array<string>, geographic_scope: Array<GeoScopeDto>, historical_window_days: number, expectations: RecordExpectationsDto, created_at: string, };
