// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the sources-memory listing surfaced to the operator.
 *
 * Mirrors [`situation_room_storage::MemorySource`] one-for-one. The
 * classifier consumes the same underlying data via
 * `ClassificationContext::sources_memory`; this DTO is the operator
 * projection of *exactly what the classifier sees* under the
 * `{{SOURCES_MEMORY}}` placeholder. Surfacing the same rows on the
 * operator side closes the principle-cleanness gap noted in the
 * Session 46 / 47 / 48 handoffs: the classifier's grounding was
 * previously invisible.
 *
 * ## Why a parallel DTO rather than re-exporting
 *
 * `MemorySource` lives in the storage crate and uses the storage
 * vocabulary (no `#[derive(TS)]`); the API crate's job is to project
 * storage types into wire DTOs. The naming difference between
 * `endpoint_url` (storage) and `url` (wire) is intentional — the
 * storage column is named after how it was historically populated;
 * the wire field is named after how it's read.
 *
 * ## Why `last_succeeded_at` rather than `last_attempted_at`
 *
 * `MemorySource::last_attempted_at` is in fact the timestamp of the
 * most-recent *successful* attempt (the SQL aggregates with
 * `MAX(CASE WHEN succeeded THEN attempted_at END)`). The storage
 * field's name predates the HAVING clause that filters to
 * success-only rows. The wire name `last_succeeded_at` is what the
 * number actually means; a future storage rename can follow.
 */
export type SourcesMemoryEntryDto = { 
/**
 * The URL the recipe fetched against successfully. Same string
 * the classifier reads under `{{SOURCES_MEMORY}}`.
 */
url: string, 
/**
 * The recipe's `source_id` — registry-shaped pre-Session-37
 * (e.g. `world_bank_indicators`), host-derived or LLM-stamped
 * post-Session-37 (e.g. `api.worldbank.org`). Both shapes coexist;
 * the classifier doesn't distinguish them and neither does this
 * surface.
 */
source_id: string, 
/**
 * Total `recipe_fetch_attempts` rows where `succeeded = true` for
 * this (URL, source_id) pair. The HAVING clause means this is
 * always ≥ 1 — sources with no successes don't appear at all.
 */
successful_attempts: number, 
/**
 * Timestamp of the most recent successful fetch attempt for the
 * pair. Ordering key on the storage side; recency-sort drives the
 * "top 30 by recency" surface the classifier sees.
 */
last_succeeded_at: string, 
/**
 * Topic-tag strings drawn from every plan whose recipes fetched
 * this URL successfully, deduplicated and alphabetised. 0..N
 * entries; bounded in practice by the plan count touching the URL.
 */
associated_topics: Array<string>, };
