// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for a registered source descriptor. Mirrors
 * [`situation_room_pipeline::research_classifier::SourceDescriptor`].
 *
 * **Doc-narrowed under ADR 0015 (Session 37).** The classifier no
 * longer reads `config/sources.toml` — it consults the in-DB sources
 * memory ([`Store::sources_memory`]). The DTO survives because the
 * wire schema is stable; the frontend never used it for
 * classification anyway, and a future "demo fixtures" surface might
 * still want it.
 */
export type SourceDescriptorDto = { id: string, display_name: string, description: string, authoritative_for: Array<string>, };
