// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for a registered source descriptor. Mirrors
 * [`situation_room_pipeline::research_classifier::SourceDescriptor`].
 *
 * Currently the frontend doesn't fetch this directly (the binary
 * loads `config/sources.toml` and stuffs descriptors into `AppState`),
 * but the type is exported so a future settings or "sources used
 * by this plan" view has a stable wire schema to import.
 */
export type SourceDescriptorDto = { id: string, display_name: string, description: string, authoritative_for: Array<string>, };
