// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for [`situation_room_core::Subjects`].
 *
 * `entities` and `topics` are flat string vecs (vocab newtypes
 * serialize as plain strings). `places` and `time` are kept
 * opaque — the frontend doesn't render places or time-scopes on
 * the record card today, and typing the full enum hierarchy
 * isn't justified until it does.
 */
export type SubjectsDto = { entities: Array<string>, 
/**
 * Place refs as opaque JSON. Each entry is one of the
 * `PlaceRef` variants; rendering picks them apart on demand.
 */
places: unknown, 
/**
 * Time scope as opaque JSON, or `None`.
 */
time: unknown | null, topics: Array<string>, };
