/**
 * situation_room API client.
 *
 * Typed wrappers around `@tauri-apps/api/core`'s `invoke()` for the
 * commands the backend exposes. The frontend should always go through
 * these wrappers — never call `invoke()` directly — so the argument
 * names and return types stay in lockstep with the Rust
 * `#[tauri::command]` signatures.
 *
 * All types are generated by `ts-rs` from `crates/api/src/types_export.rs`
 * and `crates/api/src/records_dto.rs`. Regenerate with
 * `cargo test --package situation_room-api`.
 */
import { invoke } from '@tauri-apps/api/core';

import type { ResearchPlanDto } from './types/ResearchPlanDto';
import type { PlanSummary } from './types/PlanSummary';
import type { PlanStatusDto } from './types/PlanStatusDto';
import type { CommandErrorDto } from './types/CommandErrorDto';
import type { FetchReportDto } from './types/FetchReportDto';
import type { FetchRunSummaryDto } from './types/FetchRunSummaryDto';
import type { RecipeDto } from './types/RecipeDto';
import type { RecipeFeedbackDto } from './types/RecipeFeedbackDto';
import type { RecipeFetchAttemptDto } from './types/RecipeFetchAttemptDto';
import type { RecordsByPlanDto } from './types/RecordsByPlanDto';
import type { RecipeOutcomesHistoryEntryDto } from './types/RecipeOutcomesHistoryEntryDto';
import type { ExpectationCoverageRowDto } from './types/ExpectationCoverageRowDto';

/**
 * Run Level-1 classification on a topic. Persists the resulting plan
 * (status = `pending`) and returns it. The same call flow that the
 * situation-room CLI uses.
 *
 * Throws a `CommandErrorDto` (Tauri serializes thrown command errors
 * directly) — call sites should catch and switch on `.kind`.
 */
export async function classify(topic: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('classify', { topic });
}

/**
 * List the most recent persisted plans. No LLM call; safe to invoke
 * on app startup. The backend clamps `limit` into [1, 200] regardless
 * of what the frontend sends.
 *
 * `status` filters by lifecycle state. Pass `null` (the default) to
 * see every status; pass `'pending'` / `'accepted'` / `'rejected'`
 * for the filtered listing the filter strip drives.
 */
export async function listRecentPlans(
  limit = 50,
  status: PlanStatusDto | null = null,
): Promise<PlanSummary[]> {
  return invoke<PlanSummary[]>('list_recent_plans', { limit, status });
}

/**
 * Fetch one plan by id. Throws `{ kind: 'not_found' }` if the id
 * isn't present, `{ kind: 'invalid_input' }` if the id isn't a UUID.
 */
export async function getPlan(id: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('get_plan', { id });
}

/**
 * Mark a plan as accepted. Idempotent. Returns the updated plan so
 * the caller can refresh local state without a separate `getPlan`
 * roundtrip.
 *
 * Throws `{ kind: 'not_found' }` if the id has been removed between
 * the listing fetch and this call.
 */
export async function acceptPlan(id: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('accept_plan', { id });
}

/**
 * Mark a plan as rejected, optionally attaching a free-text reason.
 * Soft-delete: the row stays for audit but is hidden from default
 * listings. Idempotent — calling twice with different reasons
 * overwrites the stored reason with the most recent one.
 *
 * `reason` is the user's note explaining why they rejected. The
 * backend validates it (length, control chars, zero-width chars,
 * bidi overrides) at the boundary; pass `null` or omit it for a
 * rejection with no note.
 *
 * Throws `{ kind: 'invalid_input', field: 'reason' }` if the note
 * fails validation. Throws `{ kind: 'not_found' }` if the id is
 * stale.
 */
export async function rejectPlan(
  id: string,
  reason: string | null = null,
): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('reject_plan', { id, reason });
}

/**
 * Re-classify a previously-rejected plan, supplying the rejection
 * note as additional context to the classifier. Produces a fresh
 * plan (new id, status = `pending`) linked back to the rejected
 * predecessor via `reclassified_from` on the new plan.
 *
 * `id` is the rejected plan's id. `editedReason`, when supplied,
 * replaces the stored rejection reason for this classification call
 * — useful when the user wants to refine their feedback before
 * retrying. When `editedReason` is `null` or omitted, the
 * predecessor's stored reason is used.
 *
 * Either the stored reason or `editedReason` must be present and
 * non-empty after validation; otherwise
 * `{ kind: 'invalid_input', field: 'reason' }` is thrown — the
 * classifier needs *some* feedback to do something different on
 * the second attempt.
 *
 * Throws `{ kind: 'invalid_input', field: 'id', message: "plan must
 * be rejected before reclassify" }` if the caller asked to
 * re-classify a plan not in `Rejected` status.
 */
export async function reclassifyPlan(
  id: string,
  editedReason: string | null = null,
): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('reclassify_plan', {
    id,
    editedReason,
  });
}

/**
 * Run the Phase-6 fetch executor against an accepted plan. One
 * synchronous call from the user's perspective: the executor loads
 * (and Level-2-authors, if needed) recipes, fetches each source,
 * applies the recipe deterministically, and writes records.
 *
 * Returns a {@link FetchReportDto} summarising what happened. Per-
 * recipe failures live inside the report's `outcomes` array; only
 * wholesale failures (plan not accepted, plan vanished, authoring
 * blew up entirely) come back as thrown {@link CommandErrorDto}.
 *
 * Throws `{ kind: 'invalid_input' }` if the plan isn't in the
 * `accepted` state.
 */
export async function runFetchForPlan(id: string): Promise<FetchReportDto> {
  return invoke<FetchReportDto>('run_fetch_for_plan', { id });
}

/**
 * List the most recent fetch runs for a plan, newest first. Pure
 * read; safe to invoke whenever the review pane needs to refresh
 * its history strip. The backend clamps `limit` to a sane range.
 */
export async function listFetchRuns(
  planId: string,
  limit = 10,
): Promise<FetchRunSummaryDto[]> {
  return invoke<FetchRunSummaryDto[]>('list_fetch_runs', { planId, limit });
}

/**
 * List the recipes authored for one plan, newest first. Pure read;
 * the recipe-inspection panel calls this on plan selection so the
 * user can see what URL / extraction spec / production bindings the
 * Level-2 author produced.
 *
 * An empty array is returned both for plans that have not yet been
 * fetched (recipes are authored on the first `run_fetch_for_plan`
 * call) and for plans whose recipes have somehow been lost. The UI
 * renders empty-state copy to cover both.
 *
 * The backend caps the result at `MAX_RECIPES_LISTING` (currently
 * 100) regardless of how many recipes exist.
 *
 * Throws `{ kind: 'invalid_input' }` if `planId` isn't a UUID.
 */
export async function listRecipesForPlan(planId: string): Promise<RecipeDto[]> {
  return invoke<RecipeDto[]>('list_recipes_for_plan', { planId });
}

/**
 * Set or clear the operator-feedback note for a (plan, source)
 * pair. ADR 0013.
 *
 * - `note: string` (non-empty after trim) — upserts; the prior note
 *   for the same (plan, source) is overwritten. Returns the
 *   persisted `RecipeFeedbackDto`.
 * - `note: null` or empty / whitespace-only — clears the row.
 *   Returns `null`.
 *
 * The backend validates the note via `check_user_text` against
 * `Bounds::RECIPE_FEEDBACK` (length, control characters, zero-width
 * chars, bidi overrides, line-ending normalization). The dialog
 * enforces a soft limit on the frontend; hard validation is the
 * trust boundary's job.
 *
 * Throws `{ kind: 'invalid_input', field: 'plan_id' | 'source_id'
 * | 'note', message }` for bad inputs; `{ kind: 'storage' }` for
 * DB-level failures.
 */
export async function setRecipeFeedback(
  planId: string,
  sourceId: string,
  note: string | null,
): Promise<RecipeFeedbackDto | null> {
  return invoke<RecipeFeedbackDto | null>('set_recipe_feedback', {
    planId,
    sourceId,
    note,
  });
}

/**
 * List every operator-feedback note attached to a plan, newest
 * first. Pure read; safe to call on plan selection. Empty list is
 * the legitimate state for a plan with no flagged recipes. ADR 0013.
 *
 * Throws `{ kind: 'invalid_input' }` if `planId` isn't a UUID.
 */
export async function listRecipeFeedbackForPlan(
  planId: string,
): Promise<RecipeFeedbackDto[]> {
  return invoke<RecipeFeedbackDto[]>('list_recipe_feedback_for_plan', {
    planId,
  });
}

/**
 * Look up the most recent recorded fetch attempt for a recipe.
 * Track A, ADR 0012 amendment 1.
 *
 * The re-author dialog calls this on mount so the operator sees the
 * exact bytes + failure message the runtime captured at the failed
 * apply, before deciding to spend an LLM call on a re-author.
 *
 * Returns the attempt for any recipe with at least one captured row
 * (today: any recipe whose latest run failed at apply stage); `null`
 * otherwise. The dialog renders empty-state copy ("no bytes captured
 * for this recipe — re-authoring may guess at the response shape")
 * when the result is `null`.
 *
 * Throws `{ kind: 'invalid_input' }` if `recipeId` isn't a UUID.
 */
export async function latestAttemptForRecipe(
  recipeId: string,
): Promise<RecipeFetchAttemptDto | null> {
  return invoke<RecipeFetchAttemptDto | null>('latest_attempt_for_recipe', {
    recipeId,
  });
}

/**
 * Manually re-author a recipe — Track A, ADR 0012 amendment 1.
 *
 * The operator triggers this after seeing a recipe fail at apply
 * stage in the fetch report. The backend:
 *
 *   1. Loads the prior recipe and the plan it belongs to.
 *   2. Pulls the bytes the runtime saw at the failed apply (captured
 *      into `recipe_fetch_attempts` at fetch time).
 *   3. Calls the LLM with the bytes + failure message + the
 *      operator's optional note.
 *   4. Persists the new recipe with `prior_recipe_id` + `reauthor_reason`.
 *
 * `recipeId` is the prior recipe's id. `operatorNote`, when supplied,
 * is the operator's correction ("the source emits unwrapped <title>,
 * not CDATA-wrapped") — the same shape as the flag-feedback note,
 * scoped to this re-author event. Empty / `null` is allowed; the
 * failure message alone may be rich enough.
 *
 * Returns the new {@link RecipeDto}; the frontend uses
 * `prior_recipe_id` and `reauthor_reason` to render the lineage chip.
 *
 * Throws:
 *  - `{ kind: 'invalid_input', field: 'recipe_id' }` — bad UUID.
 *  - `{ kind: 'invalid_input', field: 'operator_note' }` — bounds /
 *    character-class violation.
 *  - `{ kind: 'not_found' }` — recipe id (or its plan) is stale.
 *  - `{ kind: 'reauthor_failed', prior_recipe_id, message }` — no
 *    captured failed-apply bytes for this recipe (the operator
 *    should run fetch first), or the LLM authoring call failed.
 */
export async function reauthorRecipe(
  recipeId: string,
  operatorNote: string | null = null,
): Promise<RecipeDto> {
  return invoke<RecipeDto>('reauthor_recipe', {
    recipeId,
    operatorNote,
  });
}

/**
 * Return every record produced by any recipe attached to a plan,
 * bucketed by record type. Pure read; no LLM call. Session 22.
 *
 * The plan must be `accepted` or `rejected`. A `pending` plan
 * (one that has never been fetched) returns
 * `{ kind: 'invalid_input', field: 'id' }` — listing records for a
 * plan that hasn't been fetched is meaningless and would mask the
 * lifecycle state.
 *
 * The returned `RecordsByPlanDto` has six per-type Vecs. Empty
 * Vecs are the legitimate state for a bucket the plan's recipes
 * didn't produce; the frontend distinguishes "no expectations" from
 * "no records yet" by comparing the plan's expectations against
 * the bucket's records length.
 *
 * Throws `{ kind: 'invalid_input' }` if `id` isn't a UUID or the
 * plan is pending. Throws `{ kind: 'not_found' }` if the id has
 * been removed.
 */
export async function recordsForPlan(id: string): Promise<RecordsByPlanDto> {
  return invoke<RecordsByPlanDto>('records_for_plan', { id });
}

/**
 * Per-(recipe-or-source) outcome history across the plan's recent
 * fetch runs. Pure read; safe to call on plan selection.
 *
 * Each returned entry is one row in the recipe-success heatmap; each
 * `runs[i]` is one column-cell. Cells arrive ordered oldest-first so
 * the frontend renders runs left-to-right without sorting; entries
 * arrive in insertion order so recipe rows stay visually stable
 * across renders.
 *
 * `runLimit` clamps the runs (column) dimension. The backend caps it
 * at `AppState::MAX_OUTCOMES_HISTORY_RUNS` (currently 50).
 *
 * Throws `{ kind: 'invalid_input' }` if `planId` isn't a UUID.
 */
export async function recipeOutcomesHistory(
  planId: string,
  runLimit = 20,
): Promise<RecipeOutcomesHistoryEntryDto[]> {
  return invoke<RecipeOutcomesHistoryEntryDto[]>('recipe_outcomes_history', {
    planId,
    runLimit,
  });
}

/**
 * Plan-expectation coverage matrix: which recipes target which
 * expectations, plus an explicit row per uncovered expectation. Pure
 * read; safe to call on plan selection.
 *
 * Returns one row per (bucket, index) the plan declares across the
 * four binding-addressable buckets — `observation_metric`,
 * `event_type`, `entity_kind`, `relation_kind`. Document and
 * Assertion expectations aren't part of this matrix because they
 * aren't addressed by recipe `produces` bindings.
 *
 * Uncovered expectations surface with `recipes` empty so the
 * frontend can render an explicit "uncovered" marker rather than
 * silently dropping the row.
 *
 * Throws:
 *   - `{ kind: 'invalid_input' }` — `planId` isn't a UUID.
 *   - `{ kind: 'not_found' }` — plan with this id isn't in the store.
 */
export async function expectationCoverage(
  planId: string,
): Promise<ExpectationCoverageRowDto[]> {
  return invoke<ExpectationCoverageRowDto[]>('expectation_coverage', {
    planId,
  });
}

/**
 * Type guard for the discriminated union the backend throws. Tauri
 * surfaces command errors as `unknown` on the JS side; this normalizes
 * them into the typed shape so call sites can rely on `.kind`.
 *
 * If the thrown value doesn't match the expected shape, returns a
 * synthetic `Storage` variant carrying the original message — the
 * frontend should never crash because of an unrecognized error envelope.
 */
export function asCommandError(e: unknown): CommandErrorDto {
  if (
    e &&
    typeof e === 'object' &&
    'kind' in e &&
    typeof (e as { kind: unknown }).kind === 'string'
  ) {
    return e as CommandErrorDto;
  }
  const message = e instanceof Error ? e.message : String(e);
  return { kind: 'storage', message };
}
