/**
 * situation_room API client.
 *
 * Typed wrappers around `@tauri-apps/api/core`'s `invoke()` for the
 * commands the backend exposes. The frontend should always go through
 * these wrappers — never call `invoke()` directly — so the argument
 * names and return types stay in lockstep with the Rust
 * `#[tauri::command]` signatures.
 *
 * All types are generated by `ts-rs` from `crates/api/src/types_export.rs`
 * and `crates/api/src/records_dto.rs`. Regenerate with
 * `cargo test --package situation_room-api`.
 */
import { invoke } from '@tauri-apps/api/core';

import type { ResearchPlanDto } from './types/ResearchPlanDto';
import type { PlanSummary } from './types/PlanSummary';
import type { PlanStatusDto } from './types/PlanStatusDto';
import type { CommandErrorDto } from './types/CommandErrorDto';
import type { FetchReportDto } from './types/FetchReportDto';
import type { FetchRunSummaryDto } from './types/FetchRunSummaryDto';
import type { RecipeDto } from './types/RecipeDto';
import type { RecipeFeedbackDto } from './types/RecipeFeedbackDto';
import type { RecipeFetchAttemptDto } from './types/RecipeFetchAttemptDto';
import type { RecordsByPlanDto } from './types/RecordsByPlanDto';
import type { RecipeOutcomesHistoryEntryDto } from './types/RecipeOutcomesHistoryEntryDto';
import type { ExpectationCoverageRowDto } from './types/ExpectationCoverageRowDto';
import type { HostBackoffSnapshotDto } from './types/HostBackoffSnapshotDto';
import type { SourcesMemoryEntryDto } from './types/SourcesMemoryEntryDto';
import type { LlmCostLedgerEntryDto } from './types/LlmCostLedgerEntryDto';
import type { LlmCostTimelineEntryDto } from './types/LlmCostTimelineEntryDto';
import type { EntityRefreshEventDto } from './types/EntityRefreshEventDto';
import type { ClassifierPromptVersionDto } from './types/ClassifierPromptVersionDto';
import type { PromoteReportDto } from './types/PromoteReportDto';
import type { AuthorityRegistrySummaryDto } from './types/AuthorityRegistrySummaryDto';
import type { LastPromoteSummaryDto } from './types/LastPromoteSummaryDto';
import type { PromoteHistoryDto } from './types/PromoteHistoryDto';
import type { ReextractReportDto } from './types/ReextractReportDto';
import type {
  CullReportDto,
  CullPreviewItemDto,
} from './types/CullReportDto';

/**
 * Run Level-1 classification on a topic. Persists the resulting plan
 * (status = `pending`) and returns it. The same call flow that the
 * situation-room CLI uses.
 *
 * Throws a `CommandErrorDto` (Tauri serializes thrown command errors
 * directly) — call sites should catch and switch on `.kind`.
 */
export async function classify(topic: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('classify', { topic });
}

/**
 * List the most recent persisted plans. No LLM call; safe to invoke
 * on app startup. The backend clamps `limit` into [1, 200] regardless
 * of what the frontend sends.
 *
 * `status` filters by lifecycle state. Pass `null` (the default) to
 * see every status; pass `'pending'` / `'accepted'` / `'rejected'`
 * for the filtered listing the filter strip drives.
 */
export async function listRecentPlans(
  limit = 50,
  status: PlanStatusDto | null = null,
): Promise<PlanSummary[]> {
  return invoke<PlanSummary[]>('list_recent_plans', { limit, status });
}

/**
 * Fetch one plan by id. Throws `{ kind: 'not_found' }` if the id
 * isn't present, `{ kind: 'invalid_input' }` if the id isn't a UUID.
 */
export async function getPlan(id: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('get_plan', { id });
}

/**
 * Mark a plan as accepted. Idempotent. Returns the updated plan so
 * the caller can refresh local state without a separate `getPlan`
 * roundtrip.
 *
 * Throws `{ kind: 'not_found' }` if the id has been removed between
 * the listing fetch and this call.
 */
export async function acceptPlan(id: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('accept_plan', { id });
}

/**
 * Mark a plan as rejected, optionally attaching a free-text reason.
 * Soft-delete: the row stays for audit but is hidden from default
 * listings. Idempotent — calling twice with different reasons
 * overwrites the stored reason with the most recent one.
 *
 * `reason` is the user's note explaining why they rejected. The
 * backend validates it (length, control chars, zero-width chars,
 * bidi overrides) at the boundary; pass `null` or omit it for a
 * rejection with no note.
 *
 * Throws `{ kind: 'invalid_input', field: 'reason' }` if the note
 * fails validation. Throws `{ kind: 'not_found' }` if the id is
 * stale.
 */
export async function rejectPlan(
  id: string,
  reason: string | null = null,
): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('reject_plan', { id, reason });
}

/**
 * Re-classify a previously-rejected plan, supplying the rejection
 * note as additional context to the classifier. Produces a fresh
 * plan (new id, status = `pending`) linked back to the rejected
 * predecessor via `reclassified_from` on the new plan.
 *
 * `id` is the rejected plan's id. `editedReason`, when supplied,
 * replaces the stored rejection reason for this classification call
 * — useful when the user wants to refine their feedback before
 * retrying. When `editedReason` is `null` or omitted, the
 * predecessor's stored reason is used.
 *
 * Either the stored reason or `editedReason` must be present and
 * non-empty after validation; otherwise
 * `{ kind: 'invalid_input', field: 'reason' }` is thrown — the
 * classifier needs *some* feedback to do something different on
 * the second attempt.
 *
 * Throws `{ kind: 'invalid_input', field: 'id', message: "plan must
 * be rejected before reclassify" }` if the caller asked to
 * re-classify a plan not in `Rejected` status.
 */
export async function reclassifyPlan(
  id: string,
  editedReason: string | null = null,
): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('reclassify_plan', {
    id,
    editedReason,
  });
}

/**
 * Run the Phase-6 fetch executor against an accepted plan. One
 * synchronous call from the user's perspective: the executor loads
 * (and Level-2-authors, if needed) recipes, fetches each source,
 * applies the recipe deterministically, and writes records.
 *
 * Returns a {@link FetchReportDto} summarising what happened. Per-
 * recipe failures live inside the report's `outcomes` array; only
 * wholesale failures (plan not accepted, plan vanished, authoring
 * blew up entirely) come back as thrown {@link CommandErrorDto}.
 *
 * Throws `{ kind: 'invalid_input' }` if the plan isn't in the
 * `accepted` state.
 */
export async function runFetchForPlan(id: string): Promise<FetchReportDto> {
  return invoke<FetchReportDto>('run_fetch_for_plan', { id });
}

/**
 * List the most recent fetch runs for a plan, newest first. Pure
 * read; safe to invoke whenever the review pane needs to refresh
 * its history strip. The backend clamps `limit` to a sane range.
 */
export async function listFetchRuns(
  planId: string,
  limit = 10,
): Promise<FetchRunSummaryDto[]> {
  return invoke<FetchRunSummaryDto[]>('list_fetch_runs', { planId, limit });
}

/**
 * List the recipes authored for one plan, newest first. Pure read;
 * the recipe-inspection panel calls this on plan selection so the
 * user can see what URL / extraction spec / production bindings the
 * Level-2 author produced.
 *
 * An empty array is returned both for plans that have not yet been
 * fetched (recipes are authored on the first `run_fetch_for_plan`
 * call) and for plans whose recipes have somehow been lost. The UI
 * renders empty-state copy to cover both.
 *
 * The backend caps the result at `MAX_RECIPES_LISTING` (currently
 * 100) regardless of how many recipes exist.
 *
 * Throws `{ kind: 'invalid_input' }` if `planId` isn't a UUID.
 */
export async function listRecipesForPlan(planId: string): Promise<RecipeDto[]> {
  return invoke<RecipeDto[]>('list_recipes_for_plan', { planId });
}

/**
 * Set or clear the operator-feedback note for a (plan, source)
 * pair. ADR 0013.
 *
 * - `note: string` (non-empty after trim) — upserts; the prior note
 *   for the same (plan, source) is overwritten. Returns the
 *   persisted `RecipeFeedbackDto`.
 * - `note: null` or empty / whitespace-only — clears the row.
 *   Returns `null`.
 *
 * The backend validates the note via `check_user_text` against
 * `Bounds::RECIPE_FEEDBACK` (length, control characters, zero-width
 * chars, bidi overrides, line-ending normalization). The dialog
 * enforces a soft limit on the frontend; hard validation is the
 * trust boundary's job.
 *
 * Throws `{ kind: 'invalid_input', field: 'plan_id' | 'source_id'
 * | 'note', message }` for bad inputs; `{ kind: 'storage' }` for
 * DB-level failures.
 */
export async function setRecipeFeedback(
  planId: string,
  sourceId: string,
  note: string | null,
): Promise<RecipeFeedbackDto | null> {
  return invoke<RecipeFeedbackDto | null>('set_recipe_feedback', {
    planId,
    sourceId,
    note,
  });
}

/**
 * List every operator-feedback note attached to a plan, newest
 * first. Pure read; safe to call on plan selection. Empty list is
 * the legitimate state for a plan with no flagged recipes. ADR 0013.
 *
 * Throws `{ kind: 'invalid_input' }` if `planId` isn't a UUID.
 */
export async function listRecipeFeedbackForPlan(
  planId: string,
): Promise<RecipeFeedbackDto[]> {
  return invoke<RecipeFeedbackDto[]>('list_recipe_feedback_for_plan', {
    planId,
  });
}

/**
 * Look up the most recent recorded fetch attempt for a recipe.
 * Track A, ADR 0012 amendment 1.
 *
 * The re-author dialog calls this on mount so the operator sees the
 * exact bytes + failure message the runtime captured at the failed
 * apply, before deciding to spend an LLM call on a re-author.
 *
 * Returns the attempt for any recipe with at least one captured row
 * (today: any recipe whose latest run failed at apply stage); `null`
 * otherwise. The dialog renders empty-state copy ("no bytes captured
 * for this recipe — re-authoring may guess at the response shape")
 * when the result is `null`.
 *
 * Throws `{ kind: 'invalid_input' }` if `recipeId` isn't a UUID.
 */
export async function latestAttemptForRecipe(
  recipeId: string,
): Promise<RecipeFetchAttemptDto | null> {
  return invoke<RecipeFetchAttemptDto | null>('latest_attempt_for_recipe', {
    recipeId,
  });
}

/**
 * Manually re-author a recipe — Track A, ADR 0012 amendment 1.
 *
 * The operator triggers this after seeing a recipe fail at apply
 * stage in the fetch report. The backend:
 *
 *   1. Loads the prior recipe and the plan it belongs to.
 *   2. Pulls the bytes the runtime saw at the failed apply (captured
 *      into `recipe_fetch_attempts` at fetch time).
 *   3. Calls the LLM with the bytes + failure message + the
 *      operator's optional note.
 *   4. Persists the new recipe with `prior_recipe_id` + `reauthor_reason`.
 *
 * `recipeId` is the prior recipe's id. `operatorNote`, when supplied,
 * is the operator's correction ("the source emits unwrapped <title>,
 * not CDATA-wrapped") — the same shape as the flag-feedback note,
 * scoped to this re-author event. Empty / `null` is allowed; the
 * failure message alone may be rich enough.
 *
 * Returns the new {@link RecipeDto}; the frontend uses
 * `prior_recipe_id` and `reauthor_reason` to render the lineage chip.
 *
 * Throws:
 *  - `{ kind: 'invalid_input', field: 'recipe_id' }` — bad UUID.
 *  - `{ kind: 'invalid_input', field: 'operator_note' }` — bounds /
 *    character-class violation.
 *  - `{ kind: 'not_found' }` — recipe id (or its plan) is stale.
 *  - `{ kind: 'reauthor_failed', prior_recipe_id, message }` — no
 *    captured failed-apply bytes for this recipe (the operator
 *    should run fetch first), or the LLM authoring call failed.
 *  - `{ kind: 'reauthor_declined', prior_recipe_id, reason }` —
 *    **Session 66**: the LLM read the bytes + the failing recipe's
 *    selectors + the failure message and declined to author a
 *    corrected recipe. Architecturally distinct from
 *    `reauthor_failed`: nothing broke; the LLM gave a structured
 *    answer. Frontend handles this by closing the dialog cleanly
 *    and rendering the reason as a per-row decline badge instead
 *    of as an error banner.
 */
export async function reauthorRecipe(
  recipeId: string,
  operatorNote: string | null = null,
  /**
   * Session 68 follow-up — the failure message to use when no captured
   * `recipe_fetch_attempts` row exists for this recipe. Pass the
   * FetchReport outcome's `message` field for fetch-stage failures
   * (status 4xx / 5xx / timeout) — the executor doesn't capture rows
   * for those, so the backend's normal lookup returns null. When the
   * captured row exists (apply-stage failures), the override is
   * ignored. `null` keeps the pre-Session-68 behaviour.
   */
  failureMessageOverride: string | null = null,
): Promise<RecipeDto> {
  return invoke<RecipeDto>('reauthor_recipe', {
    recipeId,
    operatorNote,
    failureMessageOverride,
  });
}

/**
 * Return every record produced by any recipe attached to a plan,
 * bucketed by record type. Pure read; no LLM call. Session 22.
 *
 * The plan must be `accepted` or `rejected`. A `pending` plan
 * (one that has never been fetched) returns
 * `{ kind: 'invalid_input', field: 'id' }` — listing records for a
 * plan that hasn't been fetched is meaningless and would mask the
 * lifecycle state.
 *
 * The returned `RecordsByPlanDto` has six per-type Vecs. Empty
 * Vecs are the legitimate state for a bucket the plan's recipes
 * didn't produce; the frontend distinguishes "no expectations" from
 * "no records yet" by comparing the plan's expectations against
 * the bucket's records length.
 *
 * Throws `{ kind: 'invalid_input' }` if `id` isn't a UUID or the
 * plan is pending. Throws `{ kind: 'not_found' }` if the id has
 * been removed.
 */
export async function recordsForPlan(id: string): Promise<RecordsByPlanDto> {
  return invoke<RecordsByPlanDto>('records_for_plan', { id });
}

/**
 * Return the most recent records of each type across **all plans**.
 * Session 63. Pure read; no LLM call.
 *
 * Drives the cross-plan situation-room dashboard. The operator's
 * mental model of "what have we collected" is cumulative across
 * topics; this surface keeps prior plans' records visible after a
 * new classification lands, instead of resetting on every plan
 * change.
 *
 * `limit` caps each per-type Vec independently. The backend clamps
 * to a sane ceiling regardless of what the frontend sends. Default
 * suits the dashboard's panel densities (200 newest per type is more
 * than any single panel renders before scrolling).
 *
 * Empty buckets surface as empty Vecs, never errors. A brand-new
 * store with nothing fetched legitimately returns six empty arrays
 * — the dashboard's empty-state copy handles that case.
 *
 * No status gating, no plan-id argument. Unlike `records_for_plan`,
 * which refuses pending plans, the global query has nothing to
 * refuse.
 */
export async function recordsRecentGlobal(
  limit = 200,
): Promise<RecordsByPlanDto> {
  return invoke<RecordsByPlanDto>('records_recent_global', { limit });
}

/**
 * Per-(recipe-or-source) outcome history across the plan's recent
 * fetch runs. Pure read; safe to call on plan selection.
 *
 * Each returned entry is one row in the recipe-success heatmap; each
 * `runs[i]` is one column-cell. Cells arrive ordered oldest-first so
 * the frontend renders runs left-to-right without sorting; entries
 * arrive in insertion order so recipe rows stay visually stable
 * across renders.
 *
 * `runLimit` clamps the runs (column) dimension. The backend caps it
 * at `AppState::MAX_OUTCOMES_HISTORY_RUNS` (currently 50).
 *
 * Throws `{ kind: 'invalid_input' }` if `planId` isn't a UUID.
 */
export async function recipeOutcomesHistory(
  planId: string,
  runLimit = 20,
): Promise<RecipeOutcomesHistoryEntryDto[]> {
  return invoke<RecipeOutcomesHistoryEntryDto[]>('recipe_outcomes_history', {
    planId,
    runLimit,
  });
}

/**
 * Plan-expectation coverage matrix: which recipes target which
 * expectations, plus an explicit row per uncovered expectation. Pure
 * read; safe to call on plan selection.
 *
 * Returns one row per (bucket, index) the plan declares across the
 * four binding-addressable buckets — `observation_metric`,
 * `event_type`, `entity_kind`, `relation_kind`. Document and
 * Assertion expectations aren't part of this matrix because they
 * aren't addressed by recipe `produces` bindings.
 *
 * Uncovered expectations surface with `recipes` empty so the
 * frontend can render an explicit "uncovered" marker rather than
 * silently dropping the row.
 *
 * Throws:
 *   - `{ kind: 'invalid_input' }` — `planId` isn't a UUID.
 *   - `{ kind: 'not_found' }` — plan with this id isn't in the store.
 */
export async function expectationCoverage(
  planId: string,
): Promise<ExpectationCoverageRowDto[]> {
  return invoke<ExpectationCoverageRowDto[]>('expectation_coverage', {
    planId,
  });
}

/**
 * Per-host backoff snapshot — what the network adaptation layer has
 * observed during this binary's session (Session 48, piece B). Pure
 * read; no LLM call, no fetch.
 *
 * Returns one entry per host the layer has ever recorded a signal
 * for. Hosts whose only history is success appear with
 * `consecutive_failures = 0` and `wait_seconds_remaining = 0` — the
 * row's existence is itself the signal that the host has been
 * touched.
 *
 * Three operator-readable states from the same fields:
 *   - clean     → counter == 0, wait == 0
 *   - recovering → counter > 0, wait == 0  (schedule expired but
 *     failure history is still in effect for the next signal)
 *   - blocked   → counter > 0, wait > 0
 *
 * The state is process-local: restarting the binary clears it. There
 * is no underlying persistence; the snapshot reflects what *this*
 * session has observed.
 *
 * No source-specific routing — the host string is a runtime key, not
 * a config knob. See `HostBackoff`'s module-level rationale in the
 * pipeline crate (Session 45).
 */
export async function hostBackoffState(): Promise<HostBackoffSnapshotDto[]> {
  return invoke<HostBackoffSnapshotDto[]>('host_backoff_state');
}

/**
 * The same rows the classifier consumes under `{{SOURCES_MEMORY}}`
 * (Session 48, piece C). Pure read; no LLM call.
 *
 * Recency-sorted top-N (currently 30) of distinct (URL, source_id)
 * pairs that have at least one successful fetch attempt across all
 * plans. Carries the URL, the recipe-recorded source_id, the success
 * count, the timestamp of the most recent success, and the union of
 * topic tags from the plans the URL has appeared in.
 *
 * Empty list is the legitimate state for a fresh installation — the
 * classifier prompt teaches the cold-start pattern (emit URLs from
 * training knowledge alone). The panel renders an explicit empty
 * state in that case so the operator sees the surface but
 * understands why it's empty.
 */
export async function sourcesMemory(): Promise<SourcesMemoryEntryDto[]> {
  return invoke<SourcesMemoryEntryDto[]>('sources_memory');
}

/**
 * Snapshot of the LLM cost-by-tier ledger — one entry per
 * `(provider, tier)` bucket the binary has seen completion responses
 * for (Session 75). Pure read; no LLM call, no fetch.
 *
 * Entries arrive sorted (provider asc, tier in Frontier→Workhorse→
 * Cheap order). Counts are cumulative for the current process; the
 * ledger resets on every binary restart by design — the operator-
 * visible value is intra-session ("does the v1.22 cache lever work
 * right now?") and a process-restart-clean ledger is honest about
 * that scope.
 *
 * `calls_with_cache_data == 0` means the provider didn't report any
 * cache metadata; the dashboard tile renders that as "—" rather than
 * "0%" so the operator can tell "provider doesn't expose it" apart
 * from "cold prefix, true zero".
 */
export async function llmCostLedger(): Promise<LlmCostLedgerEntryDto[]> {
  return invoke<LlmCostLedgerEntryDto[]>('llm_cost_ledger');
}

/**
 * Session 81 — per-call cost timeline ring buffer. Sibling to
 * `llmCostLedger`: that command surfaces cumulative bucket tallies,
 * this one surfaces the 50 newest LLM completions in order, so cost
 * spikes are visible at a glance.
 *
 * Pure read; no LLM call. The ring buffer caps at 50 entries server-
 * side (`TIMELINE_CAP` on the Rust side).
 */
export async function llmCostTimeline(): Promise<LlmCostTimelineEntryDto[]> {
  return invoke<LlmCostTimelineEntryDto[]>('llm_cost_timeline');
}

/**
 * Session 99 #4 — entity-refresh-event ring buffer. Sibling to
 * `llmCostTimeline`: surfaces the 50 newest in-place refreshes on
 * the `entities` table so operators can see when Sn-98 #5's silent
 * refresh path actually fired (e.g. Lever A's LLM-extracted prose
 * name replacing a classifier slug).
 *
 * Pure read; no LLM call. The ring buffer caps at 50 entries
 * server-side (`ENTITY_REFRESH_LOG_CAP` on the Rust side).
 */
export async function entityRefreshLog(): Promise<EntityRefreshEventDto[]> {
  return invoke<EntityRefreshEventDto[]>('entity_refresh_log');
}

/**
 * Session 81 (Tauri command surface) + Session 82 (operator-facing
 * surface). Run the consensus-promotion pass for one plan and return
 * the summary report.
 *
 * Session 82 update: the same command now also runs the
 * authoritative-source fast-track pass (ADR 0004 pathway 1) when the
 * registry at `config/vocab/authoritative_sources.toml` is populated.
 * The function name and IPC contract stay stable; the
 * `authoritative_promoted` field on the returned report distinguishes
 * the two pathways.
 *
 * `minIndependentClaimants` overrides the default quorum (3) for this
 * call only. Useful for "preview consensus" sweeps on a fresh plan.
 *
 * Idempotent on re-run via content-derived dedup_keys; calling twice
 * surfaces `skipped_already_promoted > 0` on the second invocation
 * with zero new emits.
 *
 * Throws `{ kind: 'invalid_input' }` if the plan is `pending`. Throws
 * `{ kind: 'not_found' }` if the id has been removed.
 */
export async function promoteConsensusForPlan(
  id: string,
  minIndependentClaimants: number | null = null,
): Promise<PromoteReportDto> {
  return invoke<PromoteReportDto>('promote_consensus_for_plan', {
    id,
    minIndependentClaimants,
  });
}

/**
 * Session 84 — snapshot the live authoritative-source registry.
 *
 * Reads through the `LiveAuthorityRegistry` hot-reload handle on the
 * Rust side, so an operator edit to
 * `config/vocab/authoritative_sources.toml` propagates to the next
 * call within ~2 seconds (the watcher's polling cadence). Pure read;
 * no DB, no LLM.
 */
export async function authoritativeRegistrySummary(): Promise<AuthorityRegistrySummaryDto> {
  return invoke<AuthorityRegistrySummaryDto>('authoritative_registry_summary');
}

/**
 * Session 84 — return the most recent `PromoteReport` (auto-trigger
 * or manual). Returns `null` when no promote pass has run yet in
 * this binary session. Used by the dashboard tile to surface
 * "the last pass found X auth + Y consensus" without grepping INFO
 * logs.
 *
 * Session 85: derived from the promote-history ring buffer's front.
 * Behaviour is the same as Session-84 for any caller that just
 * needs the newest entry; for the full ring + cross-plan trigger
 * counter, reach for `promoteHistory`.
 */
export async function lastPromoteSummary(): Promise<LastPromoteSummaryDto | null> {
  return invoke<LastPromoteSummaryDto | null>('last_promote_summary');
}

/**
 * Session 85 — return the in-memory ring buffer of recent promote
 * passes (newest first) plus the rolling auto-trigger counter.
 *
 * The dashboard tile renders the `entries` array as a strip of
 * micro-summaries and uses `auto_triggers_last_minute` to surface a
 * "N runs in the last minute" caption when the operator fires
 * multiple plans in rapid succession (closes the visibility gap
 * Session 84 left open: the singleton "last promote" tile would
 * otherwise only show the most recent run).
 *
 * Pure read; no LLM call, no DB. Capped server-side at
 * `PROMOTE_HISTORY_CAP` (currently 20).
 */
export async function promoteHistory(): Promise<PromoteHistoryDto> {
  return invoke<PromoteHistoryDto>('promote_history');
}

/**
 * Session 92 — operator-triggered re-extraction of relation
 * Assertions from Documents already on disk. Runs the v1.2
 * `document_assertions.md` prompt (ADR 0023) against every
 * article-kind Document the plan has fetched, so the pre-Sn-91
 * Document corpus inherits the multi-claimant attribution shape
 * the prompt v1.2 lights up on net-new fetches.
 *
 * **Cost.** One workhorse-tier LLM call per article-kind Document.
 * The returned report's `documents_considered` count tells the
 * operator how many calls the next plan's re-extraction will burn.
 * No auto-trigger; per-plan operator click.
 *
 * **Idempotency.** Re-running this command produces fresh Assertion
 * rows (v1 has no per-Document dedup). `promote_consensus_for_plan`
 * dedups at the cross-source consensus layer; operators running
 * repeated re-extracts should run promote between passes.
 *
 * Throws `{ kind: 'invalid_input' }` if the plan is pending (nothing
 * fetched yet → nothing to re-extract from). Throws
 * `{ kind: 'not_found' }` if the id has been removed.
 */
export async function reextractRelationsForPlan(
  id: string,
): Promise<ReextractReportDto> {
  return invoke<ReextractReportDto>('reextract_relations_for_plan', { id });
}

/**
 * Session 93 — narrower of `reextractRelationsForPlan`, scoped to one
 * Document by id. Backs the re-extract button in the DocumentDrawer
 * header so an operator inspecting one Document can refresh just that
 * row's Assertions without paying for the full plan pass.
 *
 * Returns a `ReextractReportDto` with `documents_considered ∈ {0, 1}`
 * so the report renderer is shared with the per-plan call.
 *
 * Throws `{ kind: 'invalid_input' }` if the plan is pending, if either
 * id is malformed, or if the Document isn't in the plan's record set.
 */
export async function reextractRelationsForDocument(
  planId: string,
  documentId: string,
): Promise<ReextractReportDto> {
  return invoke<ReextractReportDto>('reextract_relations_for_document', {
    planId,
    documentId,
  });
}

/**
 * Session 93 — read-only preview of the cull pass. Returns up to
 * `DEFAULT_PREVIEW_CAP` (50) Assertion-id + path + content_kind rows
 * the destructive cull would remove. The UI surfaces this list before
 * the operator confirms the cull, matching the verify-runbook COST
 * WARNING discipline (never delete without showing what would go).
 */
export async function sampleIndexAssertionsForPlan(
  id: string,
): Promise<CullPreviewItemDto[]> {
  return invoke<CullPreviewItemDto[]>('sample_index_assertions_for_plan', {
    id,
  });
}

/**
 * Session 93 — destructive cull pass. Deletes every Assertion in the
 * plan whose source Document scores `Index` under the apply-time
 * detector. Idempotent: re-running after a successful sweep is a no-op.
 *
 * The UI MUST call `sampleIndexAssertionsForPlan` first and surface
 * its result before invoking this call — the preview is the user-
 * visible "what would go" gate.
 */
export async function cullIndexAssertionsForPlan(
  id: string,
): Promise<CullReportDto> {
  return invoke<CullReportDto>('cull_index_assertions_for_plan', { id });
}

/**
 * Session 88 — closed-vocabulary record-type tag for the
 * `record_types_for_ids` wire shape. Matches the Rust `RecordType`
 * enum's `#[serde(rename_all = "snake_case")]` form so values from
 * the IPC round-trip can be compared with `===` (no normalising
 * needed on either side).
 */
export type RecordTypeTag =
  | 'observation'
  | 'event'
  | 'entity'
  | 'relation'
  | 'document'
  | 'assertion';

/**
 * Session 88 — batch resolve a list of record UUIDs to their
 * per-table record type. Ids that resolve nowhere are simply absent
 * from the returned record; callers should treat missing entries as
 * "unknown / deleted" rather than as an error.
 *
 * Powers the PromoteDetailDrawer's per-pass `promoted_record_ids`
 * strip, which colour-codes each id chip by the record type it
 * resolved to. Generalises to any inspector that ingests a
 * heterogeneous id list.
 *
 * Throws `{ kind: 'invalid_input' }` when the batch exceeds the
 * server-side cap (500 ids) or one of the strings isn't a valid
 * UUID.
 */
export async function recordTypesForIds(
  ids: string[],
): Promise<Record<string, RecordTypeTag>> {
  return invoke<Record<string, RecordTypeTag>>('record_types_for_ids', { ids });
}

/**
 * Session 88 — fetch a single record by UUID across all six
 * per-type tables. Returns `null` when the id resolves nowhere.
 *
 * The return type is the closed-vocab Rust `Record` enum — a
 * tagged-union shape `{ kind: 'observation', observation: { … } }`
 * etc. Click-through call sites should match on `.kind` and pick
 * the matching variant payload.
 *
 * Throws `{ kind: 'invalid_input' }` when the id isn't a valid
 * UUID.
 */
export async function getRecordById(id: string): Promise<unknown | null> {
  return invoke<unknown | null>('get_record_by_id', { id });
}

/**
 * Session 77 — return the classifier prompt version currently
 * loaded in the binary. The frontend compares this against each
 * plan's `classified_by` field (`"{provider}@{version}"` for
 * post-Session-77 plans, bare provider id for pre-Session-77 plans)
 * to decide whether to render the per-plan re-classify banner.
 *
 * Pure read of a compile-time constant; no LLM call, no DB. The
 * call is cached at the store level so PlanReview doesn't refetch
 * on every plan selection.
 */
export async function classifierPromptVersion(): Promise<ClassifierPromptVersionDto> {
  return invoke<ClassifierPromptVersionDto>('classifier_prompt_version');
}

/**
 * Session 77 — parse the `classified_by` wire value into provider +
 * optional version. Lenient by design (mirrors the Rust-side
 * `parse_classifier_id`): any unparseable shape falls through to
 * `{ provider: input, promptVersion: null }` so the banner fires
 * (we'd rather over-warn than miss a stale plan).
 *
 * The split rule is the first `@` in the string. Empty version
 * (`"xai@"`) maps to `null`; empty provider (`"@2.2"`) keeps the
 * whole string under `provider`.
 */
export function parseClassifierId(
  stored: string,
): { provider: string; promptVersion: string | null } {
  const at = stored.indexOf('@');
  if (at <= 0) {
    return { provider: stored, promptVersion: null };
  }
  const version = stored.slice(at + 1);
  if (version === '') {
    return { provider: stored.slice(0, at), promptVersion: null };
  }
  return { provider: stored.slice(0, at), promptVersion: version };
}

/**
 * Session 77 — true when the plan's stored `classified_by` value is
 * pinned to `current`. Drives the re-classify banner: any plan whose
 * parsed version differs from current (or is missing entirely) is
 * "stale" and shows the banner.
 */
export function isCurrentClassifierVersion(
  classifiedBy: string,
  current: string,
): boolean {
  const { promptVersion } = parseClassifierId(classifiedBy);
  return promptVersion === current;
}

/**
 * Type guard for the discriminated union the backend throws. Tauri
 * surfaces command errors as `unknown` on the JS side; this normalizes
 * them into the typed shape so call sites can rely on `.kind`.
 *
 * If the thrown value doesn't match the expected shape, returns a
 * synthetic `Storage` variant carrying the original message — the
 * frontend should never crash because of an unrecognized error envelope.
 */
export function asCommandError(e: unknown): CommandErrorDto {
  if (
    e &&
    typeof e === 'object' &&
    'kind' in e &&
    typeof (e as { kind: unknown }).kind === 'string'
  ) {
    return e as CommandErrorDto;
  }
  const message = e instanceof Error ? e.message : String(e);
  return { kind: 'storage', message };
}
