/**
 * situation_room API client.
 *
 * Typed wrappers around `@tauri-apps/api/core`'s `invoke()` for the
 * commands the backend exposes. The frontend should always go through
 * these wrappers — never call `invoke()` directly — so the argument
 * names and return types stay in lockstep with the Rust
 * `#[tauri::command]` signatures.
 *
 * All types are generated by `ts-rs` from `crates/api/src/types_export.rs`
 * and `crates/api/src/records_dto.rs`. Regenerate with
 * `cargo test --package situation_room-api`.
 */
import { invoke } from '@tauri-apps/api/core';

import type { ResearchPlanDto } from './types/ResearchPlanDto';
import type { PlanSummary } from './types/PlanSummary';
import type { PlanStatusDto } from './types/PlanStatusDto';
import type { CommandErrorDto } from './types/CommandErrorDto';
import type { FetchReportDto } from './types/FetchReportDto';
import type { FetchRunSummaryDto } from './types/FetchRunSummaryDto';
import type { RecipeDto } from './types/RecipeDto';
import type { RecipeFeedbackDto } from './types/RecipeFeedbackDto';
import type { RecordsByPlanDto } from './types/RecordsByPlanDto';

/**
 * Run Level-1 classification on a topic. Persists the resulting plan
 * (status = `pending`) and returns it. The same call flow that the
 * situation-room CLI uses.
 *
 * Throws a `CommandErrorDto` (Tauri serializes thrown command errors
 * directly) — call sites should catch and switch on `.kind`.
 */
export async function classify(topic: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('classify', { topic });
}

/**
 * List the most recent persisted plans. No LLM call; safe to invoke
 * on app startup. The backend clamps `limit` into [1, 200] regardless
 * of what the frontend sends.
 *
 * `status` filters by lifecycle state. Pass `null` (the default) to
 * see every status; pass `'pending'` / `'accepted'` / `'rejected'`
 * for the filtered listing the filter strip drives.
 */
export async function listRecentPlans(
  limit = 50,
  status: PlanStatusDto | null = null,
): Promise<PlanSummary[]> {
  return invoke<PlanSummary[]>('list_recent_plans', { limit, status });
}

/**
 * Fetch one plan by id. Throws `{ kind: 'not_found' }` if the id
 * isn't present, `{ kind: 'invalid_input' }` if the id isn't a UUID.
 */
export async function getPlan(id: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('get_plan', { id });
}

/**
 * Mark a plan as accepted. Idempotent. Returns the updated plan so
 * the caller can refresh local state without a separate `getPlan`
 * roundtrip.
 *
 * Throws `{ kind: 'not_found' }` if the id has been removed between
 * the listing fetch and this call.
 */
export async function acceptPlan(id: string): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('accept_plan', { id });
}

/**
 * Mark a plan as rejected, optionally attaching a free-text reason.
 * Soft-delete: the row stays for audit but is hidden from default
 * listings. Idempotent — calling twice with different reasons
 * overwrites the stored reason with the most recent one.
 *
 * `reason` is the user's note explaining why they rejected. The
 * backend validates it (length, control chars, zero-width chars,
 * bidi overrides) at the boundary; pass `null` or omit it for a
 * rejection with no note.
 *
 * Throws `{ kind: 'invalid_input', field: 'reason' }` if the note
 * fails validation. Throws `{ kind: 'not_found' }` if the id is
 * stale.
 */
export async function rejectPlan(
  id: string,
  reason: string | null = null,
): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('reject_plan', { id, reason });
}

/**
 * Re-classify a previously-rejected plan, supplying the rejection
 * note as additional context to the classifier. Produces a fresh
 * plan (new id, status = `pending`) linked back to the rejected
 * predecessor via `reclassified_from` on the new plan.
 *
 * `id` is the rejected plan's id. `editedReason`, when supplied,
 * replaces the stored rejection reason for this classification call
 * — useful when the user wants to refine their feedback before
 * retrying. When `editedReason` is `null` or omitted, the
 * predecessor's stored reason is used.
 *
 * Either the stored reason or `editedReason` must be present and
 * non-empty after validation; otherwise
 * `{ kind: 'invalid_input', field: 'reason' }` is thrown — the
 * classifier needs *some* feedback to do something different on
 * the second attempt.
 *
 * Throws `{ kind: 'invalid_input', field: 'id', message: "plan must
 * be rejected before reclassify" }` if the caller asked to
 * re-classify a plan not in `Rejected` status.
 */
export async function reclassifyPlan(
  id: string,
  editedReason: string | null = null,
): Promise<ResearchPlanDto> {
  return invoke<ResearchPlanDto>('reclassify_plan', {
    id,
    editedReason,
  });
}

/**
 * Run the Phase-6 fetch executor against an accepted plan. One
 * synchronous call from the user's perspective: the executor loads
 * (and Level-2-authors, if needed) recipes, fetches each source,
 * applies the recipe deterministically, and writes records.
 *
 * Returns a {@link FetchReportDto} summarising what happened. Per-
 * recipe failures live inside the report's `outcomes` array; only
 * wholesale failures (plan not accepted, plan vanished, authoring
 * blew up entirely) come back as thrown {@link CommandErrorDto}.
 *
 * Throws `{ kind: 'invalid_input' }` if the plan isn't in the
 * `accepted` state.
 */
export async function runFetchForPlan(id: string): Promise<FetchReportDto> {
  return invoke<FetchReportDto>('run_fetch_for_plan', { id });
}

/**
 * List the most recent fetch runs for a plan, newest first. Pure
 * read; safe to invoke whenever the review pane needs to refresh
 * its history strip. The backend clamps `limit` to a sane range.
 */
export async function listFetchRuns(
  planId: string,
  limit = 10,
): Promise<FetchRunSummaryDto[]> {
  return invoke<FetchRunSummaryDto[]>('list_fetch_runs', { planId, limit });
}

/**
 * List the recipes authored for one plan, newest first. Pure read;
 * the recipe-inspection panel calls this on plan selection so the
 * user can see what URL / extraction spec / production bindings the
 * Level-2 author produced.
 *
 * An empty array is returned both for plans that have not yet been
 * fetched (recipes are authored on the first `run_fetch_for_plan`
 * call) and for plans whose recipes have somehow been lost. The UI
 * renders empty-state copy to cover both.
 *
 * The backend caps the result at `MAX_RECIPES_LISTING` (currently
 * 100) regardless of how many recipes exist.
 *
 * Throws `{ kind: 'invalid_input' }` if `planId` isn't a UUID.
 */
export async function listRecipesForPlan(planId: string): Promise<RecipeDto[]> {
  return invoke<RecipeDto[]>('list_recipes_for_plan', { planId });
}

/**
 * Set or clear the operator-feedback note for a (plan, source)
 * pair. ADR 0013.
 *
 * - `note: string` (non-empty after trim) — upserts; the prior note
 *   for the same (plan, source) is overwritten. Returns the
 *   persisted `RecipeFeedbackDto`.
 * - `note: null` or empty / whitespace-only — clears the row.
 *   Returns `null`.
 *
 * The backend validates the note via `check_user_text` against
 * `Bounds::RECIPE_FEEDBACK` (length, control characters, zero-width
 * chars, bidi overrides, line-ending normalization). The dialog
 * enforces a soft limit on the frontend; hard validation is the
 * trust boundary's job.
 *
 * Throws `{ kind: 'invalid_input', field: 'plan_id' | 'source_id'
 * | 'note', message }` for bad inputs; `{ kind: 'storage' }` for
 * DB-level failures.
 */
export async function setRecipeFeedback(
  planId: string,
  sourceId: string,
  note: string | null,
): Promise<RecipeFeedbackDto | null> {
  return invoke<RecipeFeedbackDto | null>('set_recipe_feedback', {
    planId,
    sourceId,
    note,
  });
}

/**
 * List every operator-feedback note attached to a plan, newest
 * first. Pure read; safe to call on plan selection. Empty list is
 * the legitimate state for a plan with no flagged recipes. ADR 0013.
 *
 * Throws `{ kind: 'invalid_input' }` if `planId` isn't a UUID.
 */
export async function listRecipeFeedbackForPlan(
  planId: string,
): Promise<RecipeFeedbackDto[]> {
  return invoke<RecipeFeedbackDto[]>('list_recipe_feedback_for_plan', {
    planId,
  });
}

/**
 * Return every record produced by any recipe attached to a plan,
 * bucketed by record type. Pure read; no LLM call. Session 22.
 *
 * The plan must be `accepted` or `rejected`. A `pending` plan
 * (one that has never been fetched) returns
 * `{ kind: 'invalid_input', field: 'id' }` — listing records for a
 * plan that hasn't been fetched is meaningless and would mask the
 * lifecycle state.
 *
 * The returned `RecordsByPlanDto` has six per-type Vecs. Empty
 * Vecs are the legitimate state for a bucket the plan's recipes
 * didn't produce; the frontend distinguishes "no expectations" from
 * "no records yet" by comparing the plan's expectations against
 * the bucket's records length.
 *
 * Throws `{ kind: 'invalid_input' }` if `id` isn't a UUID or the
 * plan is pending. Throws `{ kind: 'not_found' }` if the id has
 * been removed.
 */
export async function recordsForPlan(id: string): Promise<RecordsByPlanDto> {
  return invoke<RecordsByPlanDto>('records_for_plan', { id });
}

/**
 * Type guard for the discriminated union the backend throws. Tauri
 * surfaces command errors as `unknown` on the JS side; this normalizes
 * them into the typed shape so call sites can rely on `.kind`.
 *
 * If the thrown value doesn't match the expected shape, returns a
 * synthetic `Storage` variant carrying the original message — the
 * frontend should never crash because of an unrecognized error envelope.
 */
export function asCommandError(e: unknown): CommandErrorDto {
  if (
    e &&
    typeof e === 'object' &&
    'kind' in e &&
    typeof (e as { kind: unknown }).kind === 'string'
  ) {
    return e as CommandErrorDto;
  }
  const message = e instanceof Error ? e.message : String(e);
  return { kind: 'storage', message };
}
